project:
  type: website
  output-dir: docs
  
execute: 
  cache: true
  freeze: auto

website:
  title: "Biocontrole da Ferrugem do Cafeeiro"
  favicon: imgs/favicon2.png

  navbar:
   pinned: true
   background: "#323f45"
   logo: imgs/logo.png
   left:
   - text: Sobre
     icon: house
     href: index.qmd
   - text: Obtenção dos dados
     icon: clipboard
     href: about.qmd
   - text: Análise
     icon: file-code
     href: T_Hemileia.qmd
  
   right: 
     - icon: github
       href: https://github.com/niviampereira

  page-navigation: true
  page-footer: 
    left: "Copyright 2023, Nívia Maria Pereira"
    background: "#323f45"
    
format:
  html:
    fontsize: 1.1em
    theme: 
      light: sandstone
      dark: darkly
    toc: true
    code-copy: true
    code-overflow: wrap
    warning: false

editor: visual

