{
  "hash": "6875202468e63a250895e2366f6ddfc3",
  "result": {
    "markdown": "---\ntitle: \"Análise de dados do experimento de biocontrole da ferrugem do café\"\nauthor: \"Nívia Maria Pereira\"\nformat: html\neditor: visual\n---\n\n\n# Introdução\n\nO banco de dados analisado traz os resultados de um experimento realizado com trezentas plantas de café com o intuíto de testar o efeito de isolados fúngicos encontrados associados a pústulas de *Hemileia vastatrix* no controle da ferrugem do cafeeiro. Foram obtidos dados de **severidade** da doença, avaliados em 4 tempos diferentes - 30, 45, 60 e 75 dias após a inoculação (dai), **incidência** da doença e **altura das plantas**, sendo as duas últimas variáveis analisadas ao final do experimento. Neste trabalho, analisou-se 19 dos 20 tratamentos testados no experimento.\n\n# Objetivo e hipóteses\n\nPor meio da análise dos dados, objetivou-se determinar quais tratamentos testados para controle biológico de *H. vastatrix* apresentam o melhor desempenho no controle da doença, considerando as variáveis resposta severidade, incidência e altura de plantas.\n\n## Hipóteses testadas\n\n-   **Hipótese nula (H0):** Não há diferença significativa entre os tratamentos. A média da eficiência dos tratamentos no controle da doença é igual para todos os tratamentos.\n\n-   **Hipótese alternativa (Ha):** Pelo menos um dos tratamentos apresenta um desempenho significativamente melhor no controle da doença, em comparação com os demais.\n\n# Análise das variáveis resposta\n\nAs variáveis resposta foram aqui analisadas uma por vez para uma melhor compreensão do processo de análise.\n\n## Severidade da doença\n\n### Preparo pré-análise\n\n**Pacotes:** todos os pacotes utilizados no processo de análise das variáveis foram carregados previamente e utilizados no momento oportuno.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-1_67a2cdc6c23be03c8e7e9c2b34c2d540'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(googlesheets4)\nlibrary(gsheet)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(gganimate)\nlibrary(animate)\nlibrary(gifski)\nlibrary(performance)\nlibrary(DHARMa)\nlibrary(ExpDes.pt)\nlibrary(epifitter)\n```\n:::\n\n\n**Importação dos dados:** como o data frame contendo os dados de severidade estão localizados em uma uma planilha do Google Sheets, para realizar a importação dos dados necessitou-se utilizar a função `gsheet2tbl` do pacote `googlesheets4`. O data frame foi atribuído ao objeto denominado `controle`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-2_338c04793aeedbdd6794562d5cff0dd9'}\n\n```{.r .cell-code}\ncontrole <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=2004591437\")\n\ncontrole\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1,425 × 4\n   trat  tempo_dai bloco   sev\n   <chr>     <dbl> <dbl> <dbl>\n 1 E585         30     1  0.23\n 2 E585         30     1  0   \n 3 E585         30     1  0.17\n 4 E585         30     1  0.2 \n 5 E585         30     1  0   \n 6 E585         30     2  0.08\n 7 E585         30     2  0.08\n 8 E585         30     2  0   \n 9 E585         30     2  0   \n10 E585         30     2  0.73\n# ℹ 1,415 more rows\n```\n:::\n:::\n\n\n### Análise exploratória dos dados\n\nUsando o pacote `ggplot2`, foi explorado visualmente, por meio de diferentes gráficos, os dados de severidade da doença.\n\n**Gráfico de pontos:** primeiramente, visualizou-se a distribuição dos pontos de severidade nos diferentes tempos por meio de um gráfico de pontos básico. Como tem muitos pontos, para evitar sobreposição, foi usado a função `geom_jitter`, a qual promoveu a desagregação dos pontos no gráfico. Dentro desta função, definiu-se o tamanho e a quantidade de deslocamento dos pontos.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-3_b948894acf2469f44fa9adef113736ed'}\n\n```{.r .cell-code}\ncontrole |>\n  ggplot(aes(tempo_dai, sev,\n             color = trat))+\n  geom_jitter(size = 2, width = 2)+\n  theme_bw()+\n  labs(title=\"\", x=\"Time (days after inoculation)\", y = \"Disease severity (%)\", color = \"Treatments\")+\nscale_y_continuous(breaks = seq(0, 40, 5), limits = c(0, 40))+\nscale_x_continuous(breaks = seq(0, 75, 15), limits = c(0, 75))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Gráfico de pontos e linhas:** buscando uma melhor compreensão visual dos dados, uma nova abordagem foi realizada. Os dados foram agrupados, utilizando a função `group_by`, pelos tratamentos (trat) e tempo de avaliação (tempo_dai). Em seguida, calculou-se a média e o desvio padrão da variável resposta (sev) utilizando a função `summarise`. Após isso, realizou-se a plotagem do gráfico usando pontos, linhas e barra de erro para visualizar a evolução da severidade da doença ao longo do tempo, sendo cada tratamento representado por cores distintas. Para este gráfico, uma paleta de cores específica foi escolhida para os pontos e linhas ( argumento `scale_color e scale_fill_viridis`).\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-4_e876b2ec9250aeb6293cb085869d33d9'}\n\n```{.r .cell-code}\ncontrole2 <- controle |>\n  group_by(trat, tempo_dai) |>\n  summarise(sev_mean = mean(sev),\n            sev_sd = sd(sev)) \n\ncontrole2 |>\n  ggplot(aes(tempo_dai, sev_mean,\n             color = trat))+\n  geom_line(aes(group = trat, color = trat), size = 1)+\n  geom_point(aes(fill = trat), shape = 21, size = 2)+\n  scale_color_viridis_d(option = \"D\")+\n  scale_fill_viridis_d(option = \"D\")+\n  theme_bw()+\n   geom_errorbar(aes(ymin = sev_mean-sev_sd, ymax = sev_mean+sev_sd), width=0, alpha = 1)+\n  labs(title=\"\", x=\"Time (days after inoculation)\", y = \"Disease severity (%)\", color = \"Treatments\", fill = \"Treatments\")+\nscale_y_continuous(breaks = seq(0, 25, 5), limits = c(0, 25))+\nscale_x_continuous(breaks = seq(0, 75, 15), limits = c(0, 75))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n**Visualizando o avanço da severidade ao longo do tempo:** baseado no gráfico anterior, foi feito uma animação do avanço da severidade da doença para cada tratamento conforme a realização das avaliações no experimento.\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-5_c4f99082812d7f744f1d28b0f75272c6'}\n\n```{.r .cell-code}\ngif <- ggplot(controle2, aes(tempo_dai, sev_mean,\n             color = trat))+\n  geom_line(aes(group = trat, color = trat), size = 1)+\n  geom_point(aes(fill = trat), shape = 21, size = 2)+\n  scale_color_viridis_d(option = \"D\")+\n  scale_fill_viridis_d(option = \"D\")+\n  theme_bw()+\n  labs(title=\"\", x=\"Time (days after inoculation)\", y = \"Disease severity (%)\")+\nscale_y_continuous(breaks = seq(0, 25, 5), limits = c(0, 25))+\nscale_x_continuous(breaks = seq(0, 75, 15), limits = c(0, 75))\n\n#| warning: false\n#| message: false\ngif + transition_reveal(tempo_dai)\n#| warning: false\n#| message: false\ngif_sev= gif + transition_reveal(tempo_dai)\nanimate(gif_sev, height = 600, width = 600)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-5-1.gif)\n:::\n\n```{.r .cell-code}\nanim_save(\"imgs/gif_sev.gif\")\n```\n:::\n\n\n**Adição de facetas:** para visualizar separadamente os tratamentos, realizamos a adição de facetas com a função `facet_wrap`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-6_61e2ab53811517919c0d0e04396a360f'}\n\n```{.r .cell-code}\ncontrole2 |>\n  ggplot(aes(tempo_dai, sev_mean,\n             color = trat))+\n  geom_line(aes(group = trat, color = trat), size = 1)+\n  geom_point(aes(fill = trat), shape = 21, size = 2)+\n  facet_wrap(~trat)+\nscale_color_viridis_d(option = \"D\")+\n  scale_fill_viridis_d(option = \"D\")+\n  theme_bw()+\n   geom_errorbar(aes(ymin = sev_mean-sev_sd, ymax = sev_mean+sev_sd), width=0, alpha = 1)+\n  labs(title=\"\", x=\"Time (days after inoculation)\", y = \"Disease severity (%)\")+\nscale_y_continuous(breaks = seq(0, 25, 5), limits = c(0, 25))+\nscale_x_continuous(breaks = seq(0, 75, 15), limits = c(0, 75))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\nNa análise individual, pode-se inferir que os tratamentos AT, BI e HI não contiveram a severidade da doença ao longo do tempo, só aumentou com o passar das avaliações. Também é possível ver que alguns tratamentos apresentam um desvio padrão alto, o que indica que os valores estão mais afastados da média e os dados possuem alta variabilidade.\n\n**Boxplot da severidade final:** após visualizar a severidade com todos os tempos de avaliação, selecionou-se apenas a severidade final para plotar em um boxplot.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-7_e075b3b37e781315e901325eb0d320c1'}\n\n```{.r .cell-code}\nsevf <- controle |>\n  filter(tempo_dai == 75)\n\nsevf |> \n  ggplot(aes(trat, sev))+\n  geom_jitter(shape = 1, size = 1.5)+\n  geom_boxplot(fill = NA, size = .7)+\n  theme_bw()+\n  scale_y_continuous(breaks = seq(0, 37, 5), limits = c(0, 37))+\n  labs(x = \"\",\n       y = \"Final severity (%)\")\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nPor meio deste gráfico, é possível ter uma visão mais clara e distinguir quais tratamentos possibilitaram uma maior severidade da doença ao final do experimento. Considerando apenas a análise visual, os tratamentos AT, HI, BI e 58 são os piores no controle da doença.\n\n### Análise estatística e teste de hipóteses\n\n-   Hipótese nula (H0): a severidade da doença é igual para todos os tratamentos estudados.\n\n-   Hipótese alternativa (Ha): pelo menos um dos tratamentos estudados apresenta uma severidade média menor do que a média dos demais tratamentos.\n\n**Análise de variância (ANOVA):**\n\nPara a realização da ANOVA, apenas o último tempo de avaliação de severidade (75 dai) foi considerado, pois o objetivo principal era verificar quais tratamentos apresentaram menor severidade e foram mais efetivos no controle da doença. Para evitar erros, todas as células com valor ausente foram filtradas. Além disso, para ser lido e contabilizado corretamente na tabela de ANOVA, o bloco precisou ser transformado em fator. A análise do modelo de ANOVA foi realizada utilizando a função `aov`, a qual faz parte do pacote base do R. A função `summary` foi utilizada para visualização do resumo estatístico da ANOVA.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-8_9f930e2e09b156be3d9ac6920f88502d'}\n\n```{.r .cell-code}\nc2 <- controle |>\n  filter(tempo_dai == 75) |>\n  filter(sev != \"NA\")\n\nc2$bloco = as.factor(c2$bloco)\n\naov_c2 <- aov(sev ~ trat*tempo_dai + factor(bloco), data = c2)\n\nsummary(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Df Sum Sq Mean Sq F value   Pr(>F)    \ntrat           18   1928   107.1   7.125 8.89e-15 ***\nfactor(bloco)   2    793   396.3  26.367 3.63e-11 ***\nResiduals     264   3968    15.0                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nBaseado na tabela de anova, interpreta-se que, como os valores de \"p\" foram menores que o nível de significância (0,05), a hipótese nula deve ser rejeitada e a hipótese alternativa aceita. Conclui-se então que existe evidência de que pelo menos um dos tratamentos apresenta diferença estatística significativa na severidade da doença em comparação aos outros tratamentos.\n\n**Histograma dos resíduos:** para criar um histograma dos resíduos do modelo de ANOVA, foi utilizado a função `hist`. O histograma é criado a partir dos valores dos residuos armazenados no objeto `aov_c2`. Assim, podemos visualizar a distribuição dos resíduos e avaliar se eles seguem uma distribuição aproximadamente normal, o que é uma suposição importante para a validade dos resultados da ANOVA.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-9_6524595b309812f33dac98ed35d534bf'}\n\n```{.r .cell-code}\nhist (aov_c2$residuals)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nO histograma resultante mostra que os resíduos da anova não tem distribuição normal e indica a provável necessidade de transformação dos dados. Isto será melhor analisado na checagem das premissas.\n\n**Checagem das premissas:**\n\nApós a realização da anova, partiu-se para a checagem das premissas de normalidade e homocedasticidade das variâncias, as quais foram verificadas usando a função `ckeck` do pacote `performance`. A confirmação visual das premissas foi feita por meio do pacote `DHARMa`, o qual utiliza simulação para comparar os resíduos do modelo com uma distribuição de referência considerada ideal.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-10_75ef9c20d24b4ec8583632fc6b9c0604'}\n\n```{.r .cell-code}\ncheck_normality(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Non-normality of residuals detected (p < .001).\n```\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Heteroscedasticity (non-constant error variance) detected (p < .001).\n```\n:::\n\n```{.r .cell-code}\nplot(simulateResiduals(aov_c2))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nTanto a checagem pelo `performance` quanto a análise visual pelo `DHRAMa` indicaram que ambas as premissas não foram atendidas, demonstrando a necessidade de transformação dos dados.\n\n**Transformação dos dados:** utilizou-se a transformação logarítmica nos dados e obteve-se sucesso no atendimento das premissas. Para transformar os dados para o logaritimo dos números usou-se a função `log`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-11_08d048012760aa4bcbccef881fdf5e3f'}\n\n```{.r .cell-code}\nc2$bloco = as.factor(c2$bloco)\n\naov_c2 <- aov(log(sev + 0.5) ~ trat*tempo_dai + factor(bloco), data = c2)\n\nsummary(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Df Sum Sq Mean Sq F value   Pr(>F)    \ntrat           18  62.20   3.456   7.595 7.41e-16 ***\nfactor(bloco)   2  33.73  16.865  37.067 6.48e-15 ***\nResiduals     264 120.12   0.455                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n\n```{.r .cell-code}\ncheck_normality(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: residuals appear as normally distributed (p = 0.950).\n```\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(aov_c2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: Error variance appears to be homoscedastic (p = 0.072).\n```\n:::\n\n```{.r .cell-code}\nplot(simulateResiduals(aov_c2))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n**Teste de Scott-Knott:**\n\nApós a realização da análise de variância demonstrar que há diferença estatística entre os tratamentos e dos dados atenderem as premissas, foi feito o teste de `Scott-Knott` (SK) para comparação e agrupamento das médias. Escolheu-se realizar uma análise de cluster devido ao número de tratamentos.\n\nO teste de SK classifica as médias dos tratamentos de forma decrescente, fornece um quadro de ANOVA e coeficiente de variação (CV), informa se os dados atendem as premissas de normalidade e homocedasticidade e também determina se as diferenças entre os grupos são estatisticamente significativas. O teste de Scott-Knott foi feito utilizando o pacote `ExpDes.pt`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-12_d03bcd7f96858234509e20fc15563af4'}\n\n```{.r .cell-code}\nc2 <- controle |>\n  filter(tempo_dai == 75) |>\n  filter(sev != \"NA\")\n\nc2$bloco = as.factor(c2$bloco)\n\ndbc(c2$trat, factor(c2$bloco), c2$sev, quali = (TRUE), mcomp = \"sk\", sigT = 0.05,sigF = 0.05, unfold = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL     SQ     QM      Fc      Pr>Fc\nTratamento  18 1927.8 107.10  7.1249 9.0000e-15\nBloco        2  792.7 396.34 26.3667 3.6319e-11\nResiduo    264 3968.4  15.03                   \nTotal      284 6688.8                          \n------------------------------------------------------------------------\nCV = 106.5 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  1.044711e-16 \nATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.0346296 \nATENCAO: a 5% de significancia, as variancias nao podem ser consideradas homogeneas!\n------------------------------------------------------------------------\n\nTeste de Scott-Knott\n------------------------------------------------------------------------\n   Grupos Tratamentos    Medias\n1       a          AT 11.439333\n2       b          HI  8.351333\n3       b          BI  7.223333\n4       c          58  4.952667\n5       c         297  4.258000\n6       c        M230  3.456000\n7       c         290  3.263333\n8       c         ADJ  3.216000\n9       c        E486  2.904000\n10      c        E174  2.655333\n11      c        M442  2.588667\n12      c        E585  2.560667\n13      c         Mix  2.555333\n14      c        M267  2.226000\n15      c        M121  1.822667\n16      c          78  1.731333\n17      c          64  1.654000\n18      c         E48  1.172000\n19      c        E414  1.139333\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\n**Transformação dos dados:** como os dados não atenderam as premissas, foi feita a tranformação logarítmica.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-13_83560d4e2c9caefb9dc581f45652dfb9'}\n\n```{.r .cell-code}\nc2$bloco = as.factor(c2$bloco)\n\ndbc(c2$trat, factor(c2$bloco), log(c2$sev + 0.5), quali = (TRUE), mcomp = \"sk\", sigT = 0.05,sigF = 0.05, unfold = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL      SQ      QM     Fc      Pr>Fc\nTratamento  18  62.201  3.4556  7.595 7.4110e-16\nBloco        2  33.731 16.8653 37.067 6.4845e-15\nResiduo    264 120.117  0.4550                  \nTotal      284 216.049                          \n------------------------------------------------------------------------\nCV = 67.57 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  0.950314 \nDe acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.5300009 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nTeste de Scott-Knott\n------------------------------------------------------------------------\n   Grupos Tratamentos    Medias\n1       a          AT 2.1292877\n2       a          HI 1.9219884\n3       a          BI 1.6465584\n4       b         297 1.2878112\n5       b          58 1.2149423\n6       b         290 1.1440346\n7       b         ADJ 1.0217011\n8       b        E486 1.0184742\n9       b        E585 0.9342449\n10      b        E174 0.9069136\n11      b        M230 0.8677099\n12      b         Mix 0.8643519\n13      c        M442 0.7207828\n14      c        M121 0.7138208\n15      c        M267 0.6545537\n16      c          64 0.5988305\n17      c          78 0.5688595\n18      c        E414 0.3786039\n19      c         E48 0.3740960\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\nPelo teste de Scott-Knott, os tratamentos foram agrupados em 3 grupos estatisticamente distintos - \"a\", \"b\", e \"c\", sendo o grupo \"a\" formado pelas maiores médias e o \"c\" pelas menores. Como o interesse do estudo é encontrar os tratamentos que melhor controlam a doença, pela análise da variável resposta severidade, o grupo \"c\" contém os melhores tratamentos, uma vez que possue a menor média.\n\n**Visualização dos agrupamentos em boxplot:**\n\nPara visualizar a resposta dos agrupamentos dos tratamentos pelo teste SK graficamente, foi realizado a adição de uma nova coluna contendo os grupos (coluna grupo) no data frame do conjunto `c2` por meio da função `mutate`. As condições de separação dos grupos baseados nos tratamentos foi feito usando a função `case_when`. A partir disso, foi feita a plotagem do gráfico com a cor de preenchimento (fill) sendo mapeada para a coluna \"grupo\" criada anteriormente.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-14_c030a6e916fb724356ab54873059236b'}\n\n```{.r .cell-code}\nc2 <- c2 |>\n  mutate(grupo = case_when(\n    trat %in% c(\"AT\", \"HI\", \"BI\") ~ \"Group A\",\n    trat %in% c(\"297\", \"58\", \"290\", \"ADJ\", \"E486\", \"E585\", \"E174\", \"M230\", \"Mix\") ~ \"Group B\",\n    trat %in% c(\"M442\", \"M121\", \"M267\", \"64\", \"78\", \"E414\", \"E48\") ~ \"Group C\"))\n\n# Gráfico boxplot da resposta severidade, coloridos por grupos:\n\nggplot(c2, aes(trat, sev, fill = grupo)) +\n  geom_boxplot() +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  scale_x_discrete(limits = c(\"AT\", \"HI\", \"BI\", \"297\", \"58\", \"290\", \"ADJ\", \"E486\", \"E585\", \"E174\", \"M230\", \"Mix\", \"M442\", \"M121\", \"M267\", \"64\", \"78\", \"E414\", \"E48\")) +\n  labs(x = \"Treatments\") +\n  labs(y = \"Severity (%)\") +\n  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(- 20, 50)) +\n  scale_fill_manual(values = c(\"Group A\" = \"#af8dc3\", \"Group B\" = \"#67a9cf\", \"Group C\" = \"#99d594\"), name = \"Treatments groups\")\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n### Análise da Área Abaixo da Curva de Progresso da Doença (AACPD)\n\nA AACPD foi utilizada para quantificar e comparar o progresso da doença nas plantas ao longo do tempo. Como a AACPD é calculada por meio dos dados de severidade obtidos em diferentes tempos, para esta análise foram usados todos os tempos de avaliação (30, 45, 60 e 75 dai). Para a realização da análise de AACPD, foi utilizado o pacote `epifitter`.\n\n**Preparação dos dados**: Na realização desta análise, para evitar erros, foi necessário filtrar as células com dados ausentes e também o tempo zero do data frame. Os dados foram agrupados pelas variáveis `trat` e `bloco` e, por meio da função `summarise`, a variável `AACPD` foi criada e a área abaixo da curva de progresso da doença (AUPDC) calculada com base nos valores das variáveis tempo (`tempo_dai`) e severidade (`sev`). Após a criação da nova variável, o novo quadro de data frame foi visualizado utilizando o objeto `c3`. A função `summary` fornece um resumo estatístico da variável AACPD presente em `c3`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-15_515aaaee15fc64c893402f7af9e1d124'}\n\n```{.r .cell-code}\nc3 <- controle |> \n  filter(sev != \"NA\") |> \n  filter(tempo_dai != 0) |> \n  group_by(trat, bloco) |> \n  summarise(AACPD = AUDPC(tempo_dai, sev))\nc3\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 57 × 3\n# Groups:   trat [19]\n   trat  bloco AACPD\n   <chr> <dbl> <dbl>\n 1 290       1 152. \n 2 290       2 136. \n 3 290       3  51.4\n 4 297       1 471  \n 5 297       2 119. \n 6 297       3 164. \n 7 58        1 148. \n 8 58        2 105. \n 9 58        3  31.6\n10 64        1 141. \n# ℹ 47 more rows\n```\n:::\n\n```{.r .cell-code}\nsummary(c3$AACPD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  4.425  33.600  75.675 101.188 136.200 471.000 \n```\n:::\n:::\n\n\n**Agrupamento das médias com AACPD:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-16_3d4c6d60806a5496bb16302310976bc9'}\n\n```{.r .cell-code}\nc3$bloco = as.factor(c3$bloco)\n\ndbc(c3$trat, factor(c3$bloco), c3$AACPD, quali = (TRUE), mcomp = \"sk\", sigT = 0.05,sigF = 0.05, unfold = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n           GL     SQ    QM      Fc      Pr>Fc\nTratamento 18 270716 15040  3.8148 3.0854e-04\nBloco       2  98745 49373 12.5233 7.4395e-05\nResiduo    36 141929  3942                   \nTotal      56 511390                         \n------------------------------------------------------------------------\nCV = 62.05 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  0.1157226 \nDe acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.08948409 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nTeste de Scott-Knott\n------------------------------------------------------------------------\n   Grupos Tratamentos  Medias\n1       a          AT 261.425\n2       a         297 251.250\n3       a          BI 220.575\n4       b          HI 134.650\n5       b         290 113.225\n6       b        E585 107.075\n7       b         ADJ 104.850\n8       b        M230 103.850\n9       b          58  94.950\n10      b          78  82.350\n11      b         Mix  65.500\n12      b          64  64.425\n13      b        M442  63.025\n14      b        M121  59.800\n15      b        E486  52.575\n16      b        M267  48.325\n17      b        E174  43.975\n18      b        E414  38.725\n19      b         E48  12.025\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\nO teste de Scott-Knott utilizando a variável AACPD, diferente da variável severidade, agrupou os tratamentos em apenas dois grupos estatisticamente diferentes - \"a\" e \"b\". Considerando a AACPD, os tratamentos do grupo b apresentam as menores médias, sendo então considerados os melhores tratamentos.\n\nEmbora o teste de Scott-Knott tenha conseguindo separar os tratamentos em 3 grupos estatisticamente distintos para a variável resposta severidade e 2 grupos para a AACPD, no quadro de ANOVA fornecido pelo teste SK, é possível ver, na análise de ambas as variáveis, que o valor do CV está muito alto. Como o CV indica a precisão do experimento, quanto maior o seu valor, maior é a heterogeneidade e dispersão dos dados em relação à média, demostrando que existe uma baixa confiabilidade na estimativa da média.\n\n## Incidência de doença\n\n### Preparo pré-análise\n\n**Importação de dados:** os dados de incidência foram designados ao objeto `incid`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-17_33a12fcb95dc2cfaa92122e429e36e54'}\n\n```{.r .cell-code}\nincid <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733\")\n\nincid\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 285 × 7\n   trat  bloco planta   alt n_folhas folhas_ferrugem   inc\n   <chr> <dbl>  <dbl> <dbl>    <dbl>           <dbl> <dbl>\n 1 E585      1      1  40         27              12  44.4\n 2 E585      1      2  32.9       46              19  41.3\n 3 E585      1      3  39         15               9  60  \n 4 E585      1      4  38.5       52              23  44.2\n 5 E585      1      5  42         29              10  34.5\n 6 E585      2      6  33         34              26  76.5\n 7 E585      2      7  33         31              24  77.4\n 8 E585      2      8  41         19              15  78.9\n 9 E585      2      9  24.9       20              13  65  \n10 E585      2     10  31         30              20  66.7\n# ℹ 275 more rows\n```\n:::\n:::\n\n\n**Arrumando os dados:** como o data frame tem mais de uma variável resposta, fez-se necessário selecionar as colunas desejadas para trabalhar nos dados de incidência por meio da função `select` do pacote `dpylr` e também filtrar as células com ausência de dados para evitar erros durante as análises.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-18_11d49b5c145ff54c66b84e5630f7dd7e'}\n\n```{.r .cell-code}\ninc1 <- incid |>\n dplyr::select(trat, bloco, inc) |>\n  filter(inc != \"NA\")\n```\n:::\n\n\n### Análise exploratória dos dados\n\n**Boxplot:** foi feito a plotagem dos dados em um gráfico de boxplot, por meio da função `geom_boxplot` para ver o comportamento da variável incidência nos diferentes tratamentos. Utilizando o argumento `reorder` dentro da estética do ggplot, os tratamentos foram ordenados do menor para o maior valor de incidência.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-19_ee45c983f893f8346fad8c6547e41028'}\n\n```{.r .cell-code}\ninc1 |>\n  ggplot(aes(reorder(trat, inc), inc))+\n  geom_boxplot()+\n  theme_bw()+\n  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nVisualmente, os 5 piores tratamentos no controle, considerando a incidência, foram AT, 297, HI, 290 e Mix.\n\n**Gráfico de pontos com média dos dados:** as células com dados ausentes foram filtradas, os dados foram agrupados pelos tratamentos (trat) e a média e o desvio padrão da incidência foram calculados. Após isso, foi feita a plotagem do gráfico de pontos com a média dos dados e contendo a barra de erro. Os tratamentos foram ordenados da menor para a maior média de incidência.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-20_44b4e26e86b72f178c307862aa8fb9bb'}\n\n```{.r .cell-code}\ninc2 <- inc1 |>\n  filter(!is.na(inc)) |>\n  group_by(trat) |>\n  summarise(inc_mean = mean(inc),\n            inc_sd = sd(inc))\n  \ninc2 |>\n   ggplot(aes(reorder(trat, inc_mean), inc_mean))+\n  geom_point()+\n  theme_bw()+\n   geom_errorbar(aes(ymin = inc_mean-inc_sd, ymax = inc_mean+inc_sd), width=0, alpha = 1)+\n  labs(title=\"\", x=\"Treatments\", y = \" Incidence (%)\")+\nscale_y_continuous(breaks = seq(0, 100, 10), limits = c(0, 100))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n### Análise estatística e teste de hipóteses\n\n-   Hipótese nula (H0): a incidência da doença é igual para todos os tratamentos.\n\n-   Hipótese alternativa (Ha): pelo menos um dos tratamentos apresenta uma incidência média menor do que a média dos demais tratamentos.\n\n**ANOVA:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-21_ad076fbf3e243114c43ad16e31d6f6f8'}\n\n```{.r .cell-code}\ninc3 <- inc1 |>\n  filter(inc != \"NA\")\n\ninc3$bloco = as.factor(inc3$bloco)\n\naov1 <- aov(inc ~ trat + factor(bloco), data = inc3)\n\nsummary(aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Df Sum Sq Mean Sq F value   Pr(>F)    \ntrat           18  33938  1885.4   6.038 3.24e-12 ***\nfactor(bloco)   2   2783  1391.4   4.456   0.0125 *  \nResiduals     262  81808   312.2                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nBaseado na tabela de ANOVA, interpretou-se que, como o valor de p para os tratamentos foram menores que o nível de significância (0,05), deve-se rejeitar a hipótese nula, uma vez que há evidência estatística de que pelo menos um dos tratamentos diferencia-se na incidência da doença em comparação aos demais.\n\n**Histogrma dos resíduos:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-22_3d1b2f61fac6390298ab5f39eb76b791'}\n\n```{.r .cell-code}\nhist (aov1$residuals)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\nPara a variável incidência, o histograma mostra, assim como para os resíduos da anova da variável severidade, que os dados não tem distribuição normal e que, provavelmente, será necessário a transformação dos dados.\n\n**Checagem das premissas e visualização:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-23_f218647d0abab95b3de2957a20797c49'}\n\n```{.r .cell-code}\ncheck_normality(aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Non-normality of residuals detected (p = 0.005).\n```\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(aov1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: Error variance appears to be homoscedastic (p = 0.840).\n```\n:::\n\n```{.r .cell-code}\nplot(simulateResiduals(aov1))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-23-1.png){width=672}\n:::\n:::\n\n\nOs dados atenderam a premissa de homocedasticidade, mas não atenderam a normalidade pela análise do pacote `performance`. Embora isso tenha ocorrido, a visualização gráfica pelo `DHARMa` demonstra que os dados estão normais. Portanto, como visualmente os dados parecem atender às premissas de normalidade e homocedasticidade no `DHARMa`, isso diz que o modelo é apropriado para os dados, mesmo que o pacote `performance` tenha identificado desvios da normalidade. Assim, não é necessário submeter os dados a transformação.\n\n**Agrupamento de médias:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-24_e548fb0ee0a7efaf7ae15e402b8aaa6e'}\n\n```{.r .cell-code}\ninc3$bloco = as.factor(inc3$bloco)\n\ndbc(inc3$trat, factor(inc3$bloco), inc3$inc, quali = (TRUE), mcomp = \"sk\", sigT = 0.05,sigF = 0.05, unfold = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL     SQ      QM     Fc  Pr>Fc\nTratamento  18  33938 1885.44 6.0384 0.0000\nBloco        2   2783 1391.41 4.4562 0.0125\nResiduo    262  81808  312.24              \nTotal      282 118529                      \n------------------------------------------------------------------------\nCV = 27.94 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  0.005607828 \nATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.9995446 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nTeste de Scott-Knott\n------------------------------------------------------------------------\n   Grupos Tratamentos   Medias\n1       a          AT 84.50867\n2       a         297 80.26267\n3       a          HI 79.55800\n4       b         290 74.42267\n5       b         Mix 70.26867\n6       b          BI 68.67936\n7       b          58 68.16800\n8       c         ADJ 64.15667\n9       c        E585 61.55133\n10      c          78 61.53867\n11      c          64 61.13500\n12      c        E414 59.56200\n13      c        E174 58.91200\n14      c        M121 58.50133\n15      c        M230 55.36133\n16      d        E486 53.57067\n17      d        M442 50.78800\n18      d        M267 48.14707\n19      d         E48 42.65067\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\n**Transformação dos dados:** como os dados atenderam a premissa de homocedasticidade, mas não atenderam a premissa de normalidade pelo teste SK, precisou realizar a transformação logarítmica dos dados (log + 0.5).\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-25_c71a0d86729cc3b134c3869e8d5086a9'}\n\n```{.r .cell-code}\ninc3$bloco = as.factor(inc3$bloco)\n\ndbc(inc3$trat, factor(inc3$bloco), log(inc3$inc + 0.5), quali = (TRUE), mcomp = \"sk\", sigT = 0.05,sigF = 0.05, unfold = NULL)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL     SQ      QM     Fc   Pr>Fc\nTratamento  18 11.105 0.61696 4.2718 0.00000\nBloco        2  0.422 0.21104 1.4612 0.23384\nResiduo    262 37.840 0.14443               \nTotal      282 49.367                       \n------------------------------------------------------------------------\nCV = 9.3 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  1.490841e-15 \nATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.9999001 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nTeste de Scott-Knott\n------------------------------------------------------------------------\n   Grupos Tratamentos   Medias\n1       a          AT 4.426526\n2       a         297 4.377435\n3       a          HI 4.348190\n4       a         290 4.303842\n5       a         Mix 4.229844\n6       a          58 4.202431\n7       b         ADJ 4.115889\n8       b          BI 4.114462\n9       b        E585 4.090761\n10      b          64 4.063330\n11      b        E414 4.050855\n12      b        E174 4.034805\n13      b          78 4.032324\n14      b        M121 4.026069\n15      b        M230 3.983154\n16      b        E486 3.926587\n17      b        M442 3.897683\n18      c        M267 3.702856\n19      c         E48 3.688126\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\nAssim como para a variável severidade, os tratamentos foram agrupados em três grupos estatisticamente diferentes - \"a\", \"b\" e \"c\", sendo apenas 2 tratamentos agrupados em \"c\" com as menores médias e, portanto, considerados os melhores tratamentos.\n\n**Visualização dos agrupamentos em boxplot**:\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-26_af57cb22cf691182ff40cdc3c85612ff'}\n\n```{.r .cell-code}\ninc3 <- inc3 |>\n  mutate(grupo = case_when(\n    trat %in% c(\"AT\", \"HI\", \"297\", \"290\", \"58\", \"Mix\") ~ \"Group A\",\n    trat %in% c(\"BI\",\"ADJ\", \"E486\", \"E585\", \"E174\", \"M230\", \"M442\", \"M121\", \"64\", \"78\", \"E414\") ~ \"Group B\",\n    trat %in% c(\"M267\", \"E48\") ~ \"Group C\"))\n\n# Gráfico boxplot da resposta severidade, coloridos por grupos:\n\nggplot(c2, aes(trat, sev, fill = grupo)) +\n  geom_boxplot() +\n  theme_bw() +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +\n  scale_x_discrete(limits = c(\"AT\", \"HI\", \"BI\", \"297\", \"58\", \"290\", \"ADJ\", \"E486\", \"E585\", \"E174\", \"M230\", \"Mix\", \"M442\", \"M121\", \"M267\", \"64\", \"78\", \"E414\", \"E48\")) +\n  labs(x = \"Treatments\") +\n  labs(y = \"Incidence (%)\") +\n  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(-20, 50)) +\n  scale_fill_manual(values = c(\"Group A\" = \"#af8dc3\", \"Group B\" = \"#67a9cf\", \"Group C\" = \"#99d594\"), name = \"Treatments groups\")\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-26-1.png){width=672}\n:::\n:::\n\n\n## Altura de planta\n\n### Preparo pré-análise\n\n**Importação de dados:** os dados foram atribuídos ao objeto `altura`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-27_b69a253ed8f5af0ec6682e31218e5e3d'}\n\n```{.r .cell-code}\naltura <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733\")\n\naltura\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 285 × 7\n   trat  bloco planta   alt n_folhas folhas_ferrugem   inc\n   <chr> <dbl>  <dbl> <dbl>    <dbl>           <dbl> <dbl>\n 1 E585      1      1  40         27              12  44.4\n 2 E585      1      2  32.9       46              19  41.3\n 3 E585      1      3  39         15               9  60  \n 4 E585      1      4  38.5       52              23  44.2\n 5 E585      1      5  42         29              10  34.5\n 6 E585      2      6  33         34              26  76.5\n 7 E585      2      7  33         31              24  77.4\n 8 E585      2      8  41         19              15  78.9\n 9 E585      2      9  24.9       20              13  65  \n10 E585      2     10  31         30              20  66.7\n# ℹ 275 more rows\n```\n:::\n:::\n\n\n**Arrumando os dados:** como o data frame tem mais de uma variável resposta, fez-se necessário selecionar apenas os dados referentes a altura de plantas e também filtrar as células com ausência de dados no data frame para evitar erros.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-28_770ced0fdabf2202a2ce8e231c64287c'}\n\n```{.r .cell-code}\nalt1 <- altura |>\n dplyr::select(trat, bloco, alt) |>\n  filter(alt != \"NA\")\n```\n:::\n\n\n### Análise exploratória dos dados\n\n**Boxplot:** foi feito a plotagem dos dados em um boxplot para ver o comportamento da variável nos diferentes tratamentos. Os tratamentos foram ordenados, por meio da função `reorder`, da maior para a menor altura de planta.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-29_26b57d088c62dccf16269b1ec9601ca0'}\n\n```{.r .cell-code}\nalt1 |>\n  ggplot(aes(reorder(trat, alt), alt))+\n  geom_boxplot()+\n  theme_bw()+\n  scale_y_continuous(breaks = seq(0, 100, 10), limits = c(20, 60))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n**Boxplot com média dos dados:** os valores ausentes foram filtrados, os dados de altura de plantas agrupados pelos tratamentos (trat) e a média e o desvio padrão da variável resposta foram calculados. Após isso, a plotagem do boxplot foi feita com os valores de média e a barra de erro foi inserida.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-30_ba2b6688196e480f97279f0cdb357e03'}\n\n```{.r .cell-code}\nalt2 <- alt1 |>\n  filter(!is.na(alt)) |>\n  group_by(trat) |>\n  summarise(alt_mean = mean(alt),\n            alt_sd = sd(alt))\n\nalt2 |>\n  ggplot(aes(reorder(trat, alt_mean), alt_mean))+\n  geom_point()+\n  theme_bw()+\n  geom_errorbar(aes(ymin = alt_mean-alt_sd, ymax = alt_mean+alt_sd), width= 0, alpha = 1)+\n  labs(title=\"\", x=\"Treatments\", y = \"Plant height (cm)\")+\nscale_y_continuous(breaks = seq(0, 100, 10), limits = c(20, 60))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n### Análise estatística e teste de hipóteses\n\n-   Hipótese nula (H0): a altura das plantas é igual para todos os tratamentos.\n\n-   Hipótese alternativa (Ha): pelo menos um dos tratamentos apresenta uma média de altura das plantas menor do que a média dos demais tratamentos.\n\n**ANOVA:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-31_6c95f0aa1f63437fb70ebeb559e6854c'}\n\n```{.r .cell-code}\nalt3 <- alt1 |>\n  filter(alt != \"NA\")\n\nalt3$bloco = as.factor(alt3$bloco)\n\naov2 <- aov(alt ~ trat + factor(bloco), data = alt3)\n\nsummary(aov2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               Df Sum Sq Mean Sq F value Pr(>F)  \ntrat           18    999   55.51   1.233 0.2347  \nfactor(bloco)   2    216  107.76   2.393 0.0934 .\nResiduals     262  11799   45.04                 \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nCom base no resultado da ANOVA, o p-valor para a variável trat é maior que o nível de significância (0,05), o que indica que não há diferença estatistica significativa, portanto, deve-se aceitar a hipótese nula de que a média de altura é igual para todos os tratamentos.\n\n**Histograma dos resíduos:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-32_daf9287402c4da0a2dc7fda2712abc70'}\n\n```{.r .cell-code}\nhist (aov2$residuals)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\nO histogrma dos resíduos da ANOVA para a variável altura de planta mostra que a distribuição dos dados é aproximadamente normal.\n\n**Checagem das premissas:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-33_e8da1eaef1a1eb8d6a703e1066fa8c8d'}\n\n```{.r .cell-code}\ncheck_normality(aov2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: Non-normality of residuals detected (p = 0.015).\n```\n:::\n\n```{.r .cell-code}\ncheck_heteroscedasticity(aov2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOK: Error variance appears to be homoscedastic (p = 0.812).\n```\n:::\n\n```{.r .cell-code}\nplot(simulateResiduals(aov2))\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\nOs dados apresentaram-se homocedásticos, porém, não foram considerados normais pela análise do pacote `performance`. Contudo, na análsie gráfica pelo `DHARMa`, os dados atenderam ambas as premissas, assim como no caso da variável resposta incidência analisada anteriormente. Assim sendo, não é necessário submeter os dados de altura de planta a transformação.\n\n**Agrupamento de medias:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-34_8f0db100b09c7fbf4cb86b924ddd569e'}\n\n```{.r .cell-code}\nalt3$bloco = as.factor(alt3$bloco)\n\ndbc(alt3$trat, factor(alt3$bloco), alt3$alt, quali = TRUE, mcomp = \"sk\", sigT = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL      SQ      QM     Fc    Pr>Fc\nTratamento  18   999.2  55.513 1.2327 0.234654\nBloco        2   215.5 107.764 2.3929 0.093359\nResiduo    262 11799.2  45.035                \nTotal      282 13013.9                        \n------------------------------------------------------------------------\nCV = 19.4 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  0.01481312 \nATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.7716508 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nDe acordo com o teste F, as medias nao podem ser consideradas diferentes.\n   Niveis   Medias\n1     290 31.83333\n2     297 34.10000\n3      58 33.33333\n4      64 33.53571\n5      78 29.59333\n6     ADJ 36.26667\n7      AT 33.82667\n8      BI 35.22143\n9    E174 35.63333\n10   E414 34.40000\n11    E48 37.33333\n12   E486 34.66667\n13   E585 37.05333\n14     HI 35.33333\n15   M121 34.28667\n16   M230 36.48000\n17   M267 37.10000\n18   M442 33.48000\n19    Mix 33.61333\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\n**Transformação dos dados:** como os dados atenderam a premissa de homocedasticidade, mas não a premissa de normalidade, realizou-se a transformação logarítmica dos dados.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-35_8f87a25d41bc3a52da31ac18abdd3dbe'}\n\n```{.r .cell-code}\nalt3$bloco = as.factor(alt3$bloco)\n\ndbc(alt3$trat, factor(alt3$bloco), log(alt3$alt + 0.5), quali = TRUE, mcomp = \"sk\", sigT = 0.05)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n------------------------------------------------------------------------\nQuadro da analise de variancia\n------------------------------------------------------------------------\n            GL      SQ       QM     Fc    Pr>Fc\nTratamento  18  0.9402 0.052232 1.3882 0.136747\nBloco        2  0.1910 0.095508 2.5385 0.080929\nResiduo    262  9.8576 0.037625                \nTotal      282 10.9888                         \n------------------------------------------------------------------------\nCV = 5.48 %\n\n------------------------------------------------------------------------\nTeste de normalidade dos residuos \nvalor-p:  0.09134266 \nDe acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\nTeste de homogeneidade de variancia \nvalor-p:  0.8681911 \nDe acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.\n------------------------------------------------------------------------\n\nDe acordo com o teste F, as medias nao podem ser consideradas diferentes.\n   Niveis   Medias\n1     290 3.457935\n2     297 3.526061\n3      58 3.504822\n4      64 3.498774\n5      78 3.379349\n6     ADJ 3.581788\n7      AT 3.516233\n8      BI 3.560195\n9    E174 3.578536\n10   E414 3.535305\n11    E48 3.624740\n12   E486 3.535825\n13   E585 3.614540\n14     HI 3.568171\n15   M121 3.529186\n16   M230 3.591115\n17   M267 3.610197\n18   M442 3.510648\n19    Mix 3.510275\n------------------------------------------------------------------------\n```\n:::\n:::\n\n\nDe acordo com o teste F, realizado dentro do teste SK, as médias dos tratamentos não podem ser consideradas diferentes para a altura de plantas, portanto, não houve agrupamento, já que são estatisticamente iguais.\n\n**Tabela de médias pelo teste Scott-Knott**\n\nMédias de 19 tratamentos testados para controle da ferrugem do café para 3 variáveis resposta agrupadas pelo teste Scott-Knott.\n\n| Tratamentos | Severidade  | AACPD     | Incidência |\n|-------------|-------------|-----------|------------|\n| 58          | 1.2149423 b | 94.950 b  | 4.202431 a |\n| 64          | 0.5988305 c | 64.425 b  | 4.063330 b |\n| 78          | 0.5688595 c | 82.350 b  | 4.032324 b |\n| 290         | 1.1440346 b | 113.225 b | 4.303842 a |\n| 297         | 1.2878112 b | 251.250 a | 4.377435 a |\n| E48         | 0.3740960 c | 12.025 b  | 3.688126 c |\n| E174        | 0.9069136 b | 43.975 b  | 4.034805 b |\n| E414        | 0.3786039 c | 38.725 b  | 4.050855 b |\n| E486        | 1.0184742 b | 52.575 b  | 3.926587 b |\n| E585        | 0.9342449 b | 107.075 b | 4.090761 b |\n| M121        | 0.7138208 c | 59.800 b  | 4.026069 b |\n| M230        | 0.8677099 b | 103.850 b | 4.026069 b |\n| M267        | 0.6545537 c | 48.325 b  | 3.702856 c |\n| M442        | 0.7207828 c | 63.025 b  | 3.897683 b |\n| ADJ         | 1.0217011 b | 104.850 b | 4.115889 b |\n| AT          | 2.1292877 a | 261.425 a | 4.426526 a |\n| BI          | 1.6465584 a | 220.575 a | 4.114462 b |\n| HI          | 1.9219884 a | 134.650 b | 4.348190 a |\n| Mix         | 0.8643519 b | 65.500 b  | 4.229844 a |\n\n\\*Médias seguidas pela mesma letra, na mesma coluna, pertencem a um mesmo grupo (Scott-Knott). Médias transformadas (log) das variáveis severidade e incidência.\n\n# Análise de Correlação\n\nComo foram obtidas três variáveis respostas, além da AACPD calculada, e estas variáveis foram analisadas separadamente, tentou-se avaliar se essas variáveis estão correlacionadas, ou seja, se há uma associação entre elas. Por meio da análise de correlação, testou-se a seguinte hipótese:\n\n-   Hipótese nula (H0): não há correlação significativa entre as duas variáveis analisadas.\n\n-   Hipótese alternativa (Ha): há uma correlação significativa entre as duas variáveis analisadas.\n\n## Correlação entre severidade e AADPC\n\n**Preparo dos dados:** para realizar a análise de correlação entre essas duas variáveis, primeiramente foi necessário igualar o conjunto de dados de severidade para a mesma quantidade de linhas do conjunto de AACPD. Para esta análise, os dados de severidade foram atríbuidos ao conjunto `corsev`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-36_89b4d9f87ef5f3ef764aaf3d91c63507'}\n\n```{.r .cell-code}\ncorsev <- controle |> \n  filter(sev != \"NA\") |> \n  group_by(trat, bloco) |> \n  summarise(sev_mean = mean(sev))\ncorsev\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 57 × 3\n# Groups:   trat [19]\n   trat  bloco sev_mean\n   <chr> <dbl>    <dbl>\n 1 290       1    2.69 \n 2 290       2    1.85 \n 3 290       3    0.914\n 4 297       1    5.45 \n 5 297       2    1.23 \n 6 297       3    2.07 \n 7 58        1    3.50 \n 8 58        2    1.16 \n 9 58        3    1.21 \n10 64        1    2.26 \n# ℹ 47 more rows\n```\n:::\n:::\n\n\n**Teste de correlação**: para realizar o teste de correlação, usou-se a função `cor.test`, que é parte do pacote base do R.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-37_6f261de5c1fee741c3e8d37897263cd3'}\n\n```{.r .cell-code}\ncor.test(corsev$sev_mean, c3$AACPD)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  corsev$sev_mean and c3$AACPD\nt = 13.248, df = 55, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7921156 0.9232368\nsample estimates:\n      cor \n0.8725825 \n```\n:::\n:::\n\n\nO p-valor da análise da relação entre as variáveis foi menor do que o nível de significância (0,05), indicando que a hipótese nula deve ser rejeitada. Aliado a isso, a análise de correlação para as variáveis severidade e AACPD obteve um coeficiente de correlação de Pearson estimado de 0.87, sendo considerada uma correlação positiva e próxima de 1, portanto, uma correlação alta. Isso demonstra que há uma relação forte entre essas duas variáveis e que quanto mais alta a severidade média da doença, maior é a área abaixo da curva de progresso da doença.\n\n**Visualização gráfica da correlação**:\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-38_d3a99c862c9c15d2d67941fc8c87a84e'}\n\n```{.r .cell-code}\nplot(corsev$sev_mean, c3$AACPD)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n## Correlação entre incidência e altura de planta\n\n**Importação dos dados:** O teste de correlação poderia ter sido feito diretamente usando os conjuntos `inc3$inc` e `alt3$alt`, porém, não seria possível visualizar as variáveis graficamente. Então, para visualizar a possibilidade da correlação antes do teste, realizou-se a importação dos dados novamente para se trabalhar com ambas as variáveis em um único conjunto. Estas variáveis foram atríbuidas ao objeto `cor`. A função `head` foi utilizada para chamar as primeiras linhas do conjunto de dados e confirmar que os dados foram carregados de forma correta.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-39_da57e1eb60437dedf56811839c5b9c0a'}\n\n```{.r .cell-code}\ncor <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733\")\nhead(cor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 7\n  trat  bloco planta   alt n_folhas folhas_ferrugem   inc\n  <chr> <dbl>  <dbl> <dbl>    <dbl>           <dbl> <dbl>\n1 E585      1      1  40         27              12  44.4\n2 E585      1      2  32.9       46              19  41.3\n3 E585      1      3  39         15               9  60  \n4 E585      1      4  38.5       52              23  44.2\n5 E585      1      5  42         29              10  34.5\n6 E585      2      6  33         34              26  76.5\n```\n:::\n:::\n\n\n**Visualização e análise exploratória:** plotou-se os dados em um gráfico de dispersão usando a função `geom_point`, contendo em sua estética ambas as variáveis resposta. A camada com a função `geom_smooth` foi utilizada para criar uma linha de tendência. Dentro desta função, foi especificado que as barras de erro não serão exibidas no gráfico (se = \"F\") e que o método de regressão linear deve ser usado para ajustar a linha (method = \"lm\").\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-40_c5f16ae69c33c5a7bfd88c1fc6cd13c4'}\n\n```{.r .cell-code}\ncor |>\nggplot(aes(inc, alt))+\n  geom_point()+\n  geom_smooth(se = F, method = \"lm\")+\n  theme_bw()+\n  labs(x = \"Disease incidence (%)\", y = \"Plant height (cm)\") +\n  ggtitle(\"Relationship between disease incidence and plant height\")\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\nBaseado apenas na análise visual do gráfico de correlação, é possível prever que, pela direção da linha de melhor ajuste, existe uma correlação negativa entre as variáveis analisadas. A inclinação da linha parece sugerir que essa correlação não é muito forte.\n\n**Teste de correlação:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-41_c814f283d995fce420690a63221791fb'}\n\n```{.r .cell-code}\ncor2 <- cor |>\n  dplyr::select(trat, bloco, inc, alt) |>\n  filter(alt != \"NA\")\n\ncor.test(cor2$inc, cor2$alt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  cor2$inc and cor2$alt\nt = -1.0215, df = 281, p-value = 0.3079\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.17617476  0.05616917\nsample estimates:\n        cor \n-0.06082672 \n```\n:::\n:::\n\n\nO p-valor foi maior do que o nível de significância (0,05), indicando que a hipótese nula deve ser aceita. Comprovando a análise visual, o coeficiente de correlação de Pearson estimado na análise de correlação para as variáveis incidência e altura de planta foi de -0.06082672, um valor negativo e próximo de zero, o que indica que as variáveis estão negativamnete correlacionadas e possuem uma relação fraca, até mesmo próxima a inexistência. Isso quer dizer que à medida que a incidência aumenta, a altura da planta tende a diminuir.\n\n**Visualização gráfica do resultado da correlação:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-42_4e11f4273605f389b297b843ce9f4929'}\n\n```{.r .cell-code}\nplot(cor2$inc, cor2$alt)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\n## Correlação entre severidade e altura de planta\n\n**Importação dos dados:** como originalmente as variáveis resposta severidade e altura de planta pertenciam a data frames diferentes, um novo data frame foi feito contendo ambas as variáveis para viabilizar a realização da análise de correlação. Os dados foram atríbuidos ao conjunto `sev_cor`.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-43_4a953b6ab18cb3d05d8a3b7c56c28f08'}\n\n```{.r .cell-code}\nsev_cor <- gsheet2tbl(\"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1796689464\")\nhead(sev_cor)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 4\n  trat  bloco sev_final   alt\n  <chr> <dbl> <chr>     <dbl>\n1 E585      1 3.20       40  \n2 E585      1 1.47       32.9\n3 E585      1 0.48       39  \n4 E585      1 3.65       38.5\n5 E585      1 3.95       42  \n6 E585      2 5.7        33  \n```\n:::\n:::\n\n\n**Arrumando os dados:** para que não ocorressem erros durante a análise, os dados foram atríbuidos a um novo objeto chamado `sev_alt`, os dados ausentes foram filtrados e a variável severidade foi transformada de caractere para número por meio da função `mutate`. Após isso, os dados foram plotados em um gráfico de dispersão.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-44_bb28f8e09cd0dfb9b08c255f3c7bf490'}\n\n```{.r .cell-code}\nsev_alt <- sev_cor |>\n  filter(alt != \"NA\") |>\n  mutate(sev_final = as.numeric(sev_final))\n\nsev_alt |>\n  ggplot(aes(sev_final, alt))+\n  geom_point()+\n  geom_smooth(se = F, method = \"lm\")+\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nRetendo-se apenas a análise do gráfico, a direção da linha indica a tendência de uma correlação positiva entre as variáveis, mas a inclinação da linha parece demonstrar que essa correlação é fraca.\n\n**Teste de correlação:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-45_47951c49f4214c8a6a8d19dfa2b479a0'}\n\n```{.r .cell-code}\ncor.test(sev_alt$sev_final, sev_alt$alt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sev_alt$sev_final and sev_alt$alt\nt = 1.1115, df = 281, p-value = 0.2673\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.05082925  0.18135886\nsample estimates:\n       cor \n0.06616037 \n```\n:::\n:::\n\n\nO valor de p (0.2673) é maior que o nível de significância comumente adotado (0, 05), o que sugere que não há uma correlação estatisticamente significativa entre as variáveis. Além disso, o coeficiente de correlação de Pearson foi de 0.06616037, um valor próximo de zero, indicando uma correlação fraca ou inexistente entre as variáveis severidade e altura de planta.\n\n**Visualização gráfica do resultado da correlação:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-46_8794fb3bcd77110a5699b71c9ceb83a7'}\n\n```{.r .cell-code}\nplot(sev_alt$sev_final, sev_alt$alt)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\n# Análise de Regressão\n\nA análise de regressão linear foi realizada no intuíto de identificar e quantificar a relação entre as variáveis. Na análise de regressão, testou-se a hipótese nula de que não há relação entre a variável independente e a variável dependente. A hipótese alternativa é que há uma relação entre a variável independente e a variável dependente.\n\n## Efeito da severidade na altura de planta\n\nRealizamos uma análise de regressão para saber se a altura da planta tem relação com a severidade da doença, ou seja, se a variável altura de planta é dependente da severidade. Nesse caso, foi utilizado os valores da severidade final.\n\n**Visualização e análise exploratória:**\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-47_1f102654c2922dd263a504095e66657d'}\n\n```{.r .cell-code}\nsev_alt |>\n  ggplot(aes(alt,sev_final, color = trat))+\n  geom_point()+\n  geom_smooth(method =\"lm\", se =F)\n```\n\n::: {.cell-output-display}\n![](T_Hemileia_files/figure-html/unnamed-chunk-47-1.png){width=672}\n:::\n:::\n\n\n**Teste:** o teste de regressão foi realizado utilizando a função `lm`, que faz parte do pacote base do R. A função `summary` foi usada para gerar um quadro de resumo com o resultado do teste.\n\n\n::: {.cell hash='T_Hemileia_cache/html/unnamed-chunk-48_082f8d7679af1d1711a83505b2302759'}\n\n```{.r .cell-code}\nreg <- lm(alt ~ sev_final, data = sev_alt)\n\nsummary(reg)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = alt ~ sev_final, data = sev_alt)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-13.2851  -5.2659  -0.2148   5.0985  18.5103 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 34.24723    0.50534  67.770   <2e-16 ***\nsev_final    0.09237    0.08311   1.111    0.267    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.79 on 281 degrees of freedom\nMultiple R-squared:  0.004377,\tAdjusted R-squared:  0.0008341 \nF-statistic: 1.235 on 1 and 281 DF,  p-value: 0.2673\n```\n:::\n:::\n\n\nA análise de regressão indica que a severidade final não tem um efeito estatisticamente significativo na altura das plantas. O p-valor da variável severidade final é de 0.267, o que mostra a falta de evidências estatisticamente significativas de uma relação linear entre as variáveis. Aliado a isso, o valor do coeficiente de determinação (R²), que indica quanto a variável resposta altura de planta é explicada pela variável severidade final, deu muito baixo (0.004377).\n\n# Conclusão\n\nConsiderando os agrupamentos de média dos tratamentos para a variável resposta severidade, os melhores tratamentos no controle da doença (menores médias) foram: M442, M121, M267, 64, 78, E414 e E48. Já para a incidência, apenas dois tratamentos apresentaram as menores médias. Pela AACPD, mais de 8 tratamentos foram considerados estatísticamente iguais e agrupados como tendo as menores médias dentre eles, a a maioria dos considerados melhores baseado na severidade: 64, M442, M121, E486, M267, E174, E414 e E48.\n\nDiante dos resultados obtidos, conclui-se que os dados são inconclusivos e não possuem confiabilidade suficiente, uma vez que apresentam um alto coeficiente de variação e desvio padrão para a principal variável resposta analisada, fazendo com que haja uma alta variabilidasde entre os blocos. Recomenda-se a repetição do experimento utilizando um maior número de repetições para reduzir o CV e o erro experimetal. Os resultados obtidos nestas análises podem ser úteis para a exclusão dos piores tratamentos testados e seleção dos melhores tratamentos para novos experimentos.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}