<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Nívia Maria Pereira">

<title>Biocontrole da Ferrugem do Cafeeiro - Análise de dados do experimento de biocontrole da ferrugem do café</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./imgs/favicon2.png" rel="icon" type="image/png">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./imgs/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Biocontrole da Ferrugem do Cafeeiro</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"><i class="bi bi-house" role="img">
</i> 
 <span class="menu-text">Sobre</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"><i class="bi bi-clipboard" role="img">
</i> 
 <span class="menu-text">Obtenção dos dados</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./T_Hemileia.html" aria-current="page"><i class="bi bi-file-code" role="img">
</i> 
 <span class="menu-text">Análise</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/niviampereira"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução">Introdução</a></li>
  <li><a href="#objetivo-e-hipóteses" id="toc-objetivo-e-hipóteses" class="nav-link" data-scroll-target="#objetivo-e-hipóteses">Objetivo e hipóteses</a>
  <ul class="collapse">
  <li><a href="#hipóteses-testadas" id="toc-hipóteses-testadas" class="nav-link" data-scroll-target="#hipóteses-testadas">Hipóteses testadas</a></li>
  </ul></li>
  <li><a href="#análise-das-variáveis-resposta" id="toc-análise-das-variáveis-resposta" class="nav-link" data-scroll-target="#análise-das-variáveis-resposta">Análise das variáveis resposta</a>
  <ul class="collapse">
  <li><a href="#severidade-da-doença" id="toc-severidade-da-doença" class="nav-link" data-scroll-target="#severidade-da-doença">Severidade da doença</a>
  <ul class="collapse">
  <li><a href="#preparo-pré-análise" id="toc-preparo-pré-análise" class="nav-link" data-scroll-target="#preparo-pré-análise">Preparo pré-análise</a></li>
  <li><a href="#análise-exploratória-dos-dados" id="toc-análise-exploratória-dos-dados" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados">Análise exploratória dos dados</a></li>
  <li><a href="#análise-estatística-e-teste-de-hipóteses" id="toc-análise-estatística-e-teste-de-hipóteses" class="nav-link" data-scroll-target="#análise-estatística-e-teste-de-hipóteses">Análise estatística e teste de hipóteses</a></li>
  <li><a href="#análise-da-área-abaixo-da-curva-de-progresso-da-doença-aacpd" id="toc-análise-da-área-abaixo-da-curva-de-progresso-da-doença-aacpd" class="nav-link" data-scroll-target="#análise-da-área-abaixo-da-curva-de-progresso-da-doença-aacpd">Análise da Área Abaixo da Curva de Progresso da Doença (AACPD)</a></li>
  </ul></li>
  <li><a href="#incidência-de-doença" id="toc-incidência-de-doença" class="nav-link" data-scroll-target="#incidência-de-doença">Incidência de doença</a>
  <ul class="collapse">
  <li><a href="#preparo-pré-análise-1" id="toc-preparo-pré-análise-1" class="nav-link" data-scroll-target="#preparo-pré-análise-1">Preparo pré-análise</a></li>
  <li><a href="#análise-exploratória-dos-dados-1" id="toc-análise-exploratória-dos-dados-1" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados-1">Análise exploratória dos dados</a></li>
  <li><a href="#análise-estatística-e-teste-de-hipóteses-1" id="toc-análise-estatística-e-teste-de-hipóteses-1" class="nav-link" data-scroll-target="#análise-estatística-e-teste-de-hipóteses-1">Análise estatística e teste de hipóteses</a></li>
  </ul></li>
  <li><a href="#altura-de-planta" id="toc-altura-de-planta" class="nav-link" data-scroll-target="#altura-de-planta">Altura de planta</a>
  <ul class="collapse">
  <li><a href="#preparo-pré-análise-2" id="toc-preparo-pré-análise-2" class="nav-link" data-scroll-target="#preparo-pré-análise-2">Preparo pré-análise</a></li>
  <li><a href="#análise-exploratória-dos-dados-2" id="toc-análise-exploratória-dos-dados-2" class="nav-link" data-scroll-target="#análise-exploratória-dos-dados-2">Análise exploratória dos dados</a></li>
  <li><a href="#análise-estatística-e-teste-de-hipóteses-2" id="toc-análise-estatística-e-teste-de-hipóteses-2" class="nav-link" data-scroll-target="#análise-estatística-e-teste-de-hipóteses-2">Análise estatística e teste de hipóteses</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#análise-de-correlação" id="toc-análise-de-correlação" class="nav-link" data-scroll-target="#análise-de-correlação">Análise de Correlação</a>
  <ul class="collapse">
  <li><a href="#correlação-entre-severidade-e-aadpc" id="toc-correlação-entre-severidade-e-aadpc" class="nav-link" data-scroll-target="#correlação-entre-severidade-e-aadpc">Correlação entre severidade e AADPC</a></li>
  <li><a href="#correlação-entre-incidência-e-altura-de-planta" id="toc-correlação-entre-incidência-e-altura-de-planta" class="nav-link" data-scroll-target="#correlação-entre-incidência-e-altura-de-planta">Correlação entre incidência e altura de planta</a></li>
  <li><a href="#correlação-entre-severidade-e-altura-de-planta" id="toc-correlação-entre-severidade-e-altura-de-planta" class="nav-link" data-scroll-target="#correlação-entre-severidade-e-altura-de-planta">Correlação entre severidade e altura de planta</a></li>
  </ul></li>
  <li><a href="#análise-de-regressão" id="toc-análise-de-regressão" class="nav-link" data-scroll-target="#análise-de-regressão">Análise de Regressão</a>
  <ul class="collapse">
  <li><a href="#efeito-da-severidade-na-altura-de-planta" id="toc-efeito-da-severidade-na-altura-de-planta" class="nav-link" data-scroll-target="#efeito-da-severidade-na-altura-de-planta">Efeito da severidade na altura de planta</a></li>
  </ul></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão">Conclusão</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise de dados do experimento de biocontrole da ferrugem do café</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Nívia Maria Pereira </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introdução" class="level1">
<h1>Introdução</h1>
<p>O banco de dados analisado traz os resultados de um experimento realizado com trezentas plantas de café com o intuíto de testar o efeito de isolados fúngicos encontrados associados a pústulas de <em>Hemileia vastatrix</em> no controle da ferrugem do cafeeiro. Foram obtidos dados de <strong>severidade</strong> da doença, avaliados em 4 tempos diferentes - 30, 45, 60 e 75 dias após a inoculação (dai), <strong>incidência</strong> da doença e <strong>altura das plantas</strong>, sendo as duas últimas variáveis analisadas ao final do experimento. Neste trabalho, analisou-se 19 dos 20 tratamentos testados no experimento.</p>
</section>
<section id="objetivo-e-hipóteses" class="level1">
<h1>Objetivo e hipóteses</h1>
<p>Por meio da análise dos dados, objetivou-se determinar quais tratamentos testados para controle biológico de <em>H. vastatrix</em> apresentam o melhor desempenho no controle da doença, considerando as variáveis resposta severidade, incidência e altura de plantas.</p>
<section id="hipóteses-testadas" class="level2">
<h2 class="anchored" data-anchor-id="hipóteses-testadas">Hipóteses testadas</h2>
<ul>
<li><p><strong>Hipótese nula (H0):</strong> Não há diferença significativa entre os tratamentos. A média da eficiência dos tratamentos no controle da doença é igual para todos os tratamentos.</p></li>
<li><p><strong>Hipótese alternativa (Ha):</strong> Pelo menos um dos tratamentos apresenta um desempenho significativamente melhor no controle da doença, em comparação com os demais.</p></li>
</ul>
</section>
</section>
<section id="análise-das-variáveis-resposta" class="level1">
<h1>Análise das variáveis resposta</h1>
<p>As variáveis resposta foram aqui analisadas uma por vez para uma melhor compreensão do processo de análise.</p>
<section id="severidade-da-doença" class="level2">
<h2 class="anchored" data-anchor-id="severidade-da-doença">Severidade da doença</h2>
<section id="preparo-pré-análise" class="level3">
<h3 class="anchored" data-anchor-id="preparo-pré-análise">Preparo pré-análise</h3>
<p><strong>Pacotes:</strong> todos os pacotes utilizados no processo de análise das variáveis foram carregados previamente e utilizados no momento oportuno.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-1_67a2cdc6c23be03c8e7e9c2b34c2d540">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(googlesheets4)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gsheet)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gganimate)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(animate)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gifski)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(DHARMa)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ExpDes.pt)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epifitter)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Importação dos dados:</strong> como o data frame contendo os dados de severidade estão localizados em uma uma planilha do Google Sheets, para realizar a importação dos dados necessitou-se utilizar a função <code>gsheet2tbl</code> do pacote <code>googlesheets4</code>. O data frame foi atribuído ao objeto denominado <code>controle</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-2_338c04793aeedbdd6794562d5cff0dd9">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>controle <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=2004591437"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>controle</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,425 × 4
   trat  tempo_dai bloco   sev
   &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 E585         30     1  0.23
 2 E585         30     1  0   
 3 E585         30     1  0.17
 4 E585         30     1  0.2 
 5 E585         30     1  0   
 6 E585         30     2  0.08
 7 E585         30     2  0.08
 8 E585         30     2  0   
 9 E585         30     2  0   
10 E585         30     2  0.73
# ℹ 1,415 more rows</code></pre>
</div>
</div>
</section>
<section id="análise-exploratória-dos-dados" class="level3">
<h3 class="anchored" data-anchor-id="análise-exploratória-dos-dados">Análise exploratória dos dados</h3>
<p>Usando o pacote <code>ggplot2</code>, foi explorado visualmente, por meio de diferentes gráficos, os dados de severidade da doença.</p>
<p><strong>Gráfico de pontos:</strong> primeiramente, visualizou-se a distribuição dos pontos de severidade nos diferentes tempos por meio de um gráfico de pontos básico. Como tem muitos pontos, para evitar sobreposição, foi usado a função <code>geom_jitter</code>, a qual promoveu a desagregação dos pontos no gráfico. Dentro desta função, definiu-se o tamanho e a quantidade de deslocamento dos pontos.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-3_b948894acf2469f44fa9adef113736ed">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>controle <span class="sc">|&gt;</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tempo_dai, sev,</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> trat))<span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">size =</span> <span class="dv">2</span>, <span class="at">width =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Time (days after inoculation)"</span>, <span class="at">y =</span> <span class="st">"Disease severity (%)"</span>, <span class="at">color =</span> <span class="st">"Treatments"</span>)<span class="sc">+</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">40</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">40</span>))<span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">75</span>, <span class="dv">15</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Gráfico de pontos e linhas:</strong> buscando uma melhor compreensão visual dos dados, uma nova abordagem foi realizada. Os dados foram agrupados, utilizando a função <code>group_by</code>, pelos tratamentos (trat) e tempo de avaliação (tempo_dai). Em seguida, calculou-se a média e o desvio padrão da variável resposta (sev) utilizando a função <code>summarise</code>. Após isso, realizou-se a plotagem do gráfico usando pontos, linhas e barra de erro para visualizar a evolução da severidade da doença ao longo do tempo, sendo cada tratamento representado por cores distintas. Para este gráfico, uma paleta de cores específica foi escolhida para os pontos e linhas ( argumento <code>scale_color e scale_fill_viridis</code>).</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-4_e876b2ec9250aeb6293cb085869d33d9">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>controle2 <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat, tempo_dai) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sev_mean =</span> <span class="fu">mean</span>(sev),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">sev_sd =</span> <span class="fu">sd</span>(sev)) </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>controle2 <span class="sc">|&gt;</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tempo_dai, sev_mean,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> trat))<span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> trat, <span class="at">color =</span> trat), <span class="at">size =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">fill =</span> trat), <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> sev_mean<span class="sc">-</span>sev_sd, <span class="at">ymax =</span> sev_mean<span class="sc">+</span>sev_sd), <span class="at">width=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Time (days after inoculation)"</span>, <span class="at">y =</span> <span class="st">"Disease severity (%)"</span>, <span class="at">color =</span> <span class="st">"Treatments"</span>, <span class="at">fill =</span> <span class="st">"Treatments"</span>)<span class="sc">+</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">25</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">25</span>))<span class="sc">+</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">75</span>, <span class="dv">15</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Visualizando o avanço da severidade ao longo do tempo:</strong> baseado no gráfico anterior, foi feito uma animação do avanço da severidade da doença para cada tratamento conforme a realização das avaliações no experimento. Para isso, animamos o gráfico no eixo x com a variável <code>tempo_dai</code> utilizando a função <code>transaction_reveal</code>, do pacote <code>gganimate</code>. Este pacote estende o pacote <code>ggplot2</code> e implementa algumas funções para animar gráficos que normalmente seriam estáticos. A animação foi salva usando a função <code>anim_save</code> e definindo a pasta de destino, o nome e formato do arquivo.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-5_1b09d1761ac642c744d5db20fcf1c396">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>gif <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(controle2, <span class="fu">aes</span>(tempo_dai, sev_mean,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> trat))<span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> trat, <span class="at">color =</span> trat), <span class="at">size =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">fill =</span> trat), <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Time (days after inoculation)"</span>, <span class="at">y =</span> <span class="st">"Disease severity (%)"</span>)<span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">25</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">25</span>))<span class="sc">+</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">75</span>, <span class="dv">15</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">75</span>))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>gif <span class="sc">+</span> <span class="fu">transition_reveal</span>(tempo_dai)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="co">#| warning: false</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co">#| message: false</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>gif_sev<span class="ot">=</span> gif <span class="sc">+</span> <span class="fu">transition_reveal</span>(tempo_dai)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="fu">animate</span>(gif_sev)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-5-1.gif" class="img-fluid"></p>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anim_save</span>(<span class="st">"imgs/gif_sev.gif"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Adição de facetas:</strong> para visualizar separadamente os tratamentos, realizamos a adição de facetas com a função <code>facet_wrap</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-6_61e2ab53811517919c0d0e04396a360f">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>controle2 <span class="sc">|&gt;</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(tempo_dai, sev_mean,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> trat))<span class="sc">+</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> trat, <span class="at">color =</span> trat), <span class="at">size =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">fill =</span> trat), <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>trat)<span class="sc">+</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_color_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option =</span> <span class="st">"D"</span>)<span class="sc">+</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> sev_mean<span class="sc">-</span>sev_sd, <span class="at">ymax =</span> sev_mean<span class="sc">+</span>sev_sd), <span class="at">width=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Time (days after inoculation)"</span>, <span class="at">y =</span> <span class="st">"Disease severity (%)"</span>)<span class="sc">+</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">25</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">25</span>))<span class="sc">+</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">75</span>, <span class="dv">15</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">75</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Na análise individual, pode-se inferir que os tratamentos AT, BI e HI não contiveram a severidade da doença ao longo do tempo, só aumentou com o passar das avaliações. Também é possível ver que alguns tratamentos apresentam um desvio padrão alto, o que indica que os valores estão mais afastados da média e os dados possuem alta variabilidade.</p>
<p><strong>Boxplot da severidade final:</strong> após visualizar a severidade com todos os tempos de avaliação, selecionou-se apenas a severidade final para plotar em um boxplot.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-7_e075b3b37e781315e901325eb0d320c1">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>sevf <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tempo_dai <span class="sc">==</span> <span class="dv">75</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>sevf <span class="sc">|&gt;</span> </span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(trat, sev))<span class="sc">+</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="fl">1.5</span>)<span class="sc">+</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="cn">NA</span>, <span class="at">size =</span> .<span class="dv">7</span>)<span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">37</span>, <span class="dv">5</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">37</span>))<span class="sc">+</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Final severity (%)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por meio deste gráfico, é possível ter uma visão mais clara e distinguir quais tratamentos possibilitaram uma maior severidade da doença ao final do experimento. Considerando apenas a análise visual, os tratamentos AT, HI, BI e 58 são os piores no controle da doença.</p>
</section>
<section id="análise-estatística-e-teste-de-hipóteses" class="level3">
<h3 class="anchored" data-anchor-id="análise-estatística-e-teste-de-hipóteses">Análise estatística e teste de hipóteses</h3>
<ul>
<li><p>Hipótese nula (H0): a severidade da doença é igual para todos os tratamentos estudados.</p></li>
<li><p>Hipótese alternativa (Ha): pelo menos um dos tratamentos estudados apresenta uma severidade média menor do que a média dos demais tratamentos.</p></li>
</ul>
<p><strong>Análise de variância (ANOVA):</strong></p>
<p>Para a realização da ANOVA, apenas o último tempo de avaliação de severidade (75 dai) foi considerado, pois o objetivo principal era verificar quais tratamentos apresentaram menor severidade e foram mais efetivos no controle da doença. Para evitar erros, todas as células com valor ausente foram filtradas. Além disso, para ser lido e contabilizado corretamente na tabela de ANOVA, o bloco precisou ser transformado em fator. A análise do modelo de ANOVA foi realizada utilizando a função <code>aov</code>, a qual faz parte do pacote base do R. A função <code>summary</code> foi utilizada para visualização do resumo estatístico da ANOVA.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-8_9f930e2e09b156be3d9ac6920f88502d">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tempo_dai <span class="sc">==</span> <span class="dv">75</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sev <span class="sc">!=</span> <span class="st">"NA"</span>)</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>c2<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(c2<span class="sc">$</span>bloco)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>aov_c2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(sev <span class="sc">~</span> trat<span class="sc">*</span>tempo_dai <span class="sc">+</span> <span class="fu">factor</span>(bloco), <span class="at">data =</span> c2)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
trat           18   1928   107.1   7.125 8.89e-15 ***
factor(bloco)   2    793   396.3  26.367 3.63e-11 ***
Residuals     264   3968    15.0                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Baseado na tabela de anova, interpreta-se que, como os valores de “p” foram menores que o nível de significância (0,05), a hipótese nula deve ser rejeitada e a hipótese alternativa aceita. Conclui-se então que existe evidência de que pelo menos um dos tratamentos apresenta diferença estatística significativa na severidade da doença em comparação aos outros tratamentos.</p>
<p><strong>Histograma dos resíduos:</strong> para criar um histograma dos resíduos do modelo de ANOVA, foi utilizado a função <code>hist</code>. O histograma é criado a partir dos valores dos residuos armazenados no objeto <code>aov_c2</code>. Assim, podemos visualizar a distribuição dos resíduos e avaliar se eles seguem uma distribuição aproximadamente normal, o que é uma suposição importante para a validade dos resultados da ANOVA.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-9_6524595b309812f33dac98ed35d534bf">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (aov_c2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O histograma resultante mostra que os resíduos da anova não tem distribuição normal e indica a provável necessidade de transformação dos dados. Isto será melhor analisado na checagem das premissas.</p>
<p><strong>Checagem das premissas:</strong></p>
<p>Após a realização da anova, partiu-se para a checagem das premissas de normalidade e homocedasticidade das variâncias, as quais foram verificadas usando a função <code>ckeck</code> do pacote <code>performance</code>. A confirmação visual das premissas foi feita por meio do pacote <code>DHARMa</code>, o qual utiliza simulação para comparar os resíduos do modelo com uma distribuição de referência considerada ideal.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-10_75ef9c20d24b4ec8583632fc6b9c0604">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p &lt; .001).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Heteroscedasticity (non-constant error variance) detected (p &lt; .001).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(aov_c2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Tanto a checagem pelo <code>performance</code> quanto a análise visual pelo <code>DHRAMa</code> indicaram que ambas as premissas não foram atendidas, demonstrando a necessidade de transformação dos dados.</p>
<p><strong>Transformação dos dados:</strong> utilizou-se a transformação logarítmica nos dados e obteve-se sucesso no atendimento das premissas. Para transformar os dados para o logaritimo dos números usou-se a função <code>log</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-11_08d048012760aa4bcbccef881fdf5e3f">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>c2<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(c2<span class="sc">$</span>bloco)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>aov_c2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(sev <span class="sc">+</span> <span class="fl">0.5</span>) <span class="sc">~</span> trat<span class="sc">*</span>tempo_dai <span class="sc">+</span> <span class="fu">factor</span>(bloco), <span class="at">data =</span> c2)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
trat           18  62.20   3.456   7.595 7.41e-16 ***
factor(bloco)   2  33.73  16.865  37.067 6.48e-15 ***
Residuals     264 120.12   0.455                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.950).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(aov_c2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.072).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(aov_c2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Teste de Scott-Knott:</strong></p>
<p>Após a realização da análise de variância demonstrar que há diferença estatística entre os tratamentos e dos dados atenderem as premissas, foi feito o teste de <code>Scott-Knott</code> (SK) para comparação e agrupamento das médias. Escolheu-se realizar uma análise de cluster devido ao número de tratamentos.</p>
<p>O teste de SK classifica as médias dos tratamentos de forma decrescente, fornece um quadro de ANOVA e coeficiente de variação (CV), informa se os dados atendem as premissas de normalidade e homocedasticidade e também determina se as diferenças entre os grupos são estatisticamente significativas. O teste de Scott-Knott foi feito utilizando o pacote <code>ExpDes.pt</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-12_d03bcd7f96858234509e20fc15563af4">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tempo_dai <span class="sc">==</span> <span class="dv">75</span>) <span class="sc">|&gt;</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sev <span class="sc">!=</span> <span class="st">"NA"</span>)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>c2<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(c2<span class="sc">$</span>bloco)</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(c2<span class="sc">$</span>trat, <span class="fu">factor</span>(c2<span class="sc">$</span>bloco), c2<span class="sc">$</span>sev, <span class="at">quali =</span> (<span class="cn">TRUE</span>), <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>,<span class="at">sigF =</span> <span class="fl">0.05</span>, <span class="at">unfold =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL     SQ     QM      Fc      Pr&gt;Fc
Tratamento  18 1927.8 107.10  7.1249 9.0000e-15
Bloco        2  792.7 396.34 26.3667 3.6319e-11
Residuo    264 3968.4  15.03                   
Total      284 6688.8                          
------------------------------------------------------------------------
CV = 106.5 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  1.044711e-16 
ATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.0346296 
ATENCAO: a 5% de significancia, as variancias nao podem ser consideradas homogeneas!
------------------------------------------------------------------------

Teste de Scott-Knott
------------------------------------------------------------------------
   Grupos Tratamentos    Medias
1       a          AT 11.439333
2       b          HI  8.351333
3       b          BI  7.223333
4       c          58  4.952667
5       c         297  4.258000
6       c        M230  3.456000
7       c         290  3.263333
8       c         ADJ  3.216000
9       c        E486  2.904000
10      c        E174  2.655333
11      c        M442  2.588667
12      c        E585  2.560667
13      c         Mix  2.555333
14      c        M267  2.226000
15      c        M121  1.822667
16      c          78  1.731333
17      c          64  1.654000
18      c         E48  1.172000
19      c        E414  1.139333
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>Transformação dos dados:</strong> como os dados não atenderam as premissas, foi feita a tranformação logarítmica.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-13_83560d4e2c9caefb9dc581f45652dfb9">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>c2<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(c2<span class="sc">$</span>bloco)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(c2<span class="sc">$</span>trat, <span class="fu">factor</span>(c2<span class="sc">$</span>bloco), <span class="fu">log</span>(c2<span class="sc">$</span>sev <span class="sc">+</span> <span class="fl">0.5</span>), <span class="at">quali =</span> (<span class="cn">TRUE</span>), <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>,<span class="at">sigF =</span> <span class="fl">0.05</span>, <span class="at">unfold =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL      SQ      QM     Fc      Pr&gt;Fc
Tratamento  18  62.201  3.4556  7.595 7.4110e-16
Bloco        2  33.731 16.8653 37.067 6.4845e-15
Residuo    264 120.117  0.4550                  
Total      284 216.049                          
------------------------------------------------------------------------
CV = 67.57 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  0.950314 
De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.5300009 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

Teste de Scott-Knott
------------------------------------------------------------------------
   Grupos Tratamentos    Medias
1       a          AT 2.1292877
2       a          HI 1.9219884
3       a          BI 1.6465584
4       b         297 1.2878112
5       b          58 1.2149423
6       b         290 1.1440346
7       b         ADJ 1.0217011
8       b        E486 1.0184742
9       b        E585 0.9342449
10      b        E174 0.9069136
11      b        M230 0.8677099
12      b         Mix 0.8643519
13      c        M442 0.7207828
14      c        M121 0.7138208
15      c        M267 0.6545537
16      c          64 0.5988305
17      c          78 0.5688595
18      c        E414 0.3786039
19      c         E48 0.3740960
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Pelo teste de Scott-Knott, os tratamentos foram agrupados em 3 grupos estatisticamente distintos - “a”, “b”, e “c”, sendo o grupo “a” formado pelas maiores médias e o “c” pelas menores. Como o interesse do estudo é encontrar os tratamentos que melhor controlam a doença, pela análise da variável resposta severidade, o grupo “c” contém os melhores tratamentos, uma vez que possue a menor média.</p>
<p><strong>Visualização dos agrupamentos em boxplot:</strong></p>
<p>Para visualizar a resposta dos agrupamentos dos tratamentos pelo teste SK graficamente, foi realizado a adição de uma nova coluna contendo os grupos (coluna grupo) no data frame do conjunto <code>c2</code> por meio da função <code>mutate</code>. As condições de separação dos grupos baseados nos tratamentos foi feito usando a função <code>case_when</code>. A partir disso, foi feita a plotagem do gráfico com a cor de preenchimento (fill) sendo mapeada para a coluna “grupo” criada anteriormente.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-14_c030a6e916fb724356ab54873059236b">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>c2 <span class="ot">&lt;-</span> c2 <span class="sc">|&gt;</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="fu">case_when</span>(</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AT"</span>, <span class="st">"HI"</span>, <span class="st">"BI"</span>) <span class="sc">~</span> <span class="st">"Group A"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"297"</span>, <span class="st">"58"</span>, <span class="st">"290"</span>, <span class="st">"ADJ"</span>, <span class="st">"E486"</span>, <span class="st">"E585"</span>, <span class="st">"E174"</span>, <span class="st">"M230"</span>, <span class="st">"Mix"</span>) <span class="sc">~</span> <span class="st">"Group B"</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"M442"</span>, <span class="st">"M121"</span>, <span class="st">"M267"</span>, <span class="st">"64"</span>, <span class="st">"78"</span>, <span class="st">"E414"</span>, <span class="st">"E48"</span>) <span class="sc">~</span> <span class="st">"Group C"</span>))</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico boxplot da resposta severidade, coloridos por grupos:</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(c2, <span class="fu">aes</span>(trat, sev, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"AT"</span>, <span class="st">"HI"</span>, <span class="st">"BI"</span>, <span class="st">"297"</span>, <span class="st">"58"</span>, <span class="st">"290"</span>, <span class="st">"ADJ"</span>, <span class="st">"E486"</span>, <span class="st">"E585"</span>, <span class="st">"E174"</span>, <span class="st">"M230"</span>, <span class="st">"Mix"</span>, <span class="st">"M442"</span>, <span class="st">"M121"</span>, <span class="st">"M267"</span>, <span class="st">"64"</span>, <span class="st">"78"</span>, <span class="st">"E414"</span>, <span class="st">"E48"</span>)) <span class="sc">+</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Treatments"</span>) <span class="sc">+</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Severity (%)"</span>) <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span> <span class="dv">20</span>, <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Group A"</span> <span class="ot">=</span> <span class="st">"#af8dc3"</span>, <span class="st">"Group B"</span> <span class="ot">=</span> <span class="st">"#67a9cf"</span>, <span class="st">"Group C"</span> <span class="ot">=</span> <span class="st">"#99d594"</span>), <span class="at">name =</span> <span class="st">"Treatments groups"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análise-da-área-abaixo-da-curva-de-progresso-da-doença-aacpd" class="level3">
<h3 class="anchored" data-anchor-id="análise-da-área-abaixo-da-curva-de-progresso-da-doença-aacpd">Análise da Área Abaixo da Curva de Progresso da Doença (AACPD)</h3>
<p>A AACPD foi utilizada para quantificar e comparar o progresso da doença nas plantas ao longo do tempo. Como a AACPD é calculada por meio dos dados de severidade obtidos em diferentes tempos, para esta análise foram usados todos os tempos de avaliação (30, 45, 60 e 75 dai). Para a realização da análise de AACPD, foi utilizado o pacote <code>epifitter</code>.</p>
<p><strong>Preparação dos dados</strong>: Na realização desta análise, para evitar erros, foi necessário filtrar as células com dados ausentes e também o tempo zero do data frame. Os dados foram agrupados pelas variáveis <code>trat</code> e <code>bloco</code> e, por meio da função <code>summarise</code>, a variável <code>AACPD</code> foi criada e a área abaixo da curva de progresso da doença (AUPDC) calculada com base nos valores das variáveis tempo (<code>tempo_dai</code>) e severidade (<code>sev</code>). Após a criação da nova variável, o novo quadro de data frame foi visualizado utilizando o objeto <code>c3</code>. A função <code>summary</code> fornece um resumo estatístico da variável AACPD presente em <code>c3</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-15_515aaaee15fc64c893402f7af9e1d124">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>c3 <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sev <span class="sc">!=</span> <span class="st">"NA"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(tempo_dai <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">|&gt;</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat, bloco) <span class="sc">|&gt;</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">AACPD =</span> <span class="fu">AUDPC</span>(tempo_dai, sev))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>c3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 57 × 3
# Groups:   trat [19]
   trat  bloco AACPD
   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
 1 290       1 152. 
 2 290       2 136. 
 3 290       3  51.4
 4 297       1 471  
 5 297       2 119. 
 6 297       3 164. 
 7 58        1 148. 
 8 58        2 105. 
 9 58        3  31.6
10 64        1 141. 
# ℹ 47 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(c3<span class="sc">$</span>AACPD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  4.425  33.600  75.675 101.188 136.200 471.000 </code></pre>
</div>
</div>
<p><strong>Agrupamento das médias com AACPD:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-16_3d4c6d60806a5496bb16302310976bc9">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>c3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(c3<span class="sc">$</span>bloco)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(c3<span class="sc">$</span>trat, <span class="fu">factor</span>(c3<span class="sc">$</span>bloco), c3<span class="sc">$</span>AACPD, <span class="at">quali =</span> (<span class="cn">TRUE</span>), <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>,<span class="at">sigF =</span> <span class="fl">0.05</span>, <span class="at">unfold =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
           GL     SQ    QM      Fc      Pr&gt;Fc
Tratamento 18 270716 15040  3.8148 3.0854e-04
Bloco       2  98745 49373 12.5233 7.4395e-05
Residuo    36 141929  3942                   
Total      56 511390                         
------------------------------------------------------------------------
CV = 62.05 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  0.1157226 
De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.08948409 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

Teste de Scott-Knott
------------------------------------------------------------------------
   Grupos Tratamentos  Medias
1       a          AT 261.425
2       a         297 251.250
3       a          BI 220.575
4       b          HI 134.650
5       b         290 113.225
6       b        E585 107.075
7       b         ADJ 104.850
8       b        M230 103.850
9       b          58  94.950
10      b          78  82.350
11      b         Mix  65.500
12      b          64  64.425
13      b        M442  63.025
14      b        M121  59.800
15      b        E486  52.575
16      b        M267  48.325
17      b        E174  43.975
18      b        E414  38.725
19      b         E48  12.025
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>O teste de Scott-Knott utilizando a variável AACPD, diferente da variável severidade, agrupou os tratamentos em apenas dois grupos estatisticamente diferentes - “a” e “b”. Considerando a AACPD, os tratamentos do grupo b apresentam as menores médias, sendo então considerados os melhores tratamentos.</p>
<p>Embora o teste de Scott-Knott tenha conseguindo separar os tratamentos em 3 grupos estatisticamente distintos para a variável resposta severidade e 2 grupos para a AACPD, no quadro de ANOVA fornecido pelo teste SK, é possível ver, na análise de ambas as variáveis, que o valor do CV está muito alto. Como o CV indica a precisão do experimento, quanto maior o seu valor, maior é a heterogeneidade e dispersão dos dados em relação à média, demostrando que existe uma baixa confiabilidade na estimativa da média.</p>
</section>
</section>
<section id="incidência-de-doença" class="level2">
<h2 class="anchored" data-anchor-id="incidência-de-doença">Incidência de doença</h2>
<section id="preparo-pré-análise-1" class="level3">
<h3 class="anchored" data-anchor-id="preparo-pré-análise-1">Preparo pré-análise</h3>
<p><strong>Importação de dados:</strong> os dados de incidência foram designados ao objeto <code>incid</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-17_33a12fcb95dc2cfaa92122e429e36e54">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>incid <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733"</span>)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>incid</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 285 × 7
   trat  bloco planta   alt n_folhas folhas_ferrugem   inc
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;
 1 E585      1      1  40         27              12  44.4
 2 E585      1      2  32.9       46              19  41.3
 3 E585      1      3  39         15               9  60  
 4 E585      1      4  38.5       52              23  44.2
 5 E585      1      5  42         29              10  34.5
 6 E585      2      6  33         34              26  76.5
 7 E585      2      7  33         31              24  77.4
 8 E585      2      8  41         19              15  78.9
 9 E585      2      9  24.9       20              13  65  
10 E585      2     10  31         30              20  66.7
# ℹ 275 more rows</code></pre>
</div>
</div>
<p><strong>Arrumando os dados:</strong> como o data frame tem mais de uma variável resposta, fez-se necessário selecionar as colunas desejadas para trabalhar nos dados de incidência por meio da função <code>select</code> do pacote <code>dpylr</code> e também filtrar as células com ausência de dados para evitar erros durante as análises.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-18_11d49b5c145ff54c66b84e5630f7dd7e">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>inc1 <span class="ot">&lt;-</span> incid <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a> dplyr<span class="sc">::</span><span class="fu">select</span>(trat, bloco, inc) <span class="sc">|&gt;</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(inc <span class="sc">!=</span> <span class="st">"NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análise-exploratória-dos-dados-1" class="level3">
<h3 class="anchored" data-anchor-id="análise-exploratória-dos-dados-1">Análise exploratória dos dados</h3>
<p><strong>Boxplot:</strong> foi feito a plotagem dos dados em um gráfico de boxplot, por meio da função <code>geom_boxplot</code> para ver o comportamento da variável incidência nos diferentes tratamentos. Utilizando o argumento <code>reorder</code> dentro da estética do ggplot, os tratamentos foram ordenados do menor para o maior valor de incidência.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-19_ee45c983f893f8346fad8c6547e41028">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>inc1 <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">reorder</span>(trat, inc), inc))<span class="sc">+</span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Visualmente, os 5 piores tratamentos no controle, considerando a incidência, foram AT, 297, HI, 290 e Mix.</p>
<p><strong>Gráfico de pontos com média dos dados:</strong> as células com dados ausentes foram filtradas, os dados foram agrupados pelos tratamentos (trat) e a média e o desvio padrão da incidência foram calculados. Após isso, foi feita a plotagem do gráfico de pontos com a média dos dados e contendo a barra de erro. Os tratamentos foram ordenados da menor para a maior média de incidência.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-20_44b4e26e86b72f178c307862aa8fb9bb">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>inc2 <span class="ot">&lt;-</span> inc1 <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(inc)) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat) <span class="sc">|&gt;</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">inc_mean =</span> <span class="fu">mean</span>(inc),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">inc_sd =</span> <span class="fu">sd</span>(inc))</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>inc2 <span class="sc">|&gt;</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">reorder</span>(trat, inc_mean), inc_mean))<span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> inc_mean<span class="sc">-</span>inc_sd, <span class="at">ymax =</span> inc_mean<span class="sc">+</span>inc_sd), <span class="at">width=</span><span class="dv">0</span>, <span class="at">alpha =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Treatments"</span>, <span class="at">y =</span> <span class="st">" Incidence (%)"</span>)<span class="sc">+</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análise-estatística-e-teste-de-hipóteses-1" class="level3">
<h3 class="anchored" data-anchor-id="análise-estatística-e-teste-de-hipóteses-1">Análise estatística e teste de hipóteses</h3>
<ul>
<li><p>Hipótese nula (H0): a incidência da doença é igual para todos os tratamentos.</p></li>
<li><p>Hipótese alternativa (Ha): pelo menos um dos tratamentos apresenta uma incidência média menor do que a média dos demais tratamentos.</p></li>
</ul>
<p><strong>ANOVA:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-21_ad076fbf3e243114c43ad16e31d6f6f8">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>inc3 <span class="ot">&lt;-</span> inc1 <span class="sc">|&gt;</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(inc <span class="sc">!=</span> <span class="st">"NA"</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>inc3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(inc3<span class="sc">$</span>bloco)</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>aov1 <span class="ot">&lt;-</span> <span class="fu">aov</span>(inc <span class="sc">~</span> trat <span class="sc">+</span> <span class="fu">factor</span>(bloco), <span class="at">data =</span> inc3)</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value   Pr(&gt;F)    
trat           18  33938  1885.4   6.038 3.24e-12 ***
factor(bloco)   2   2783  1391.4   4.456   0.0125 *  
Residuals     262  81808   312.2                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Baseado na tabela de ANOVA, interpretou-se que, como o valor de p para os tratamentos foram menores que o nível de significância (0,05), deve-se rejeitar a hipótese nula, uma vez que há evidência estatística de que pelo menos um dos tratamentos diferencia-se na incidência da doença em comparação aos demais.</p>
<p><strong>Histogrma dos resíduos:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-22_3d1b2f61fac6390298ab5f39eb76b791">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (aov1<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Para a variável incidência, o histograma mostra, assim como para os resíduos da anova da variável severidade, que os dados não tem distribuição normal e que, provavelmente, será necessário a transformação dos dados.</p>
<p><strong>Checagem das premissas e visualização:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-23_f218647d0abab95b3de2957a20797c49">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(aov1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.005).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(aov1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.840).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(aov1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Os dados atenderam a premissa de homocedasticidade, mas não atenderam a normalidade pela análise do pacote <code>performance</code>. Embora isso tenha ocorrido, a visualização gráfica pelo <code>DHARMa</code> demonstra que os dados estão normais. Portanto, como visualmente os dados parecem atender às premissas de normalidade e homocedasticidade no <code>DHARMa</code>, isso diz que o modelo é apropriado para os dados, mesmo que o pacote <code>performance</code> tenha identificado desvios da normalidade. Assim, não é necessário submeter os dados a transformação.</p>
<p><strong>Agrupamento de médias:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-24_e548fb0ee0a7efaf7ae15e402b8aaa6e">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>inc3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(inc3<span class="sc">$</span>bloco)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(inc3<span class="sc">$</span>trat, <span class="fu">factor</span>(inc3<span class="sc">$</span>bloco), inc3<span class="sc">$</span>inc, <span class="at">quali =</span> (<span class="cn">TRUE</span>), <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>,<span class="at">sigF =</span> <span class="fl">0.05</span>, <span class="at">unfold =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL     SQ      QM     Fc  Pr&gt;Fc
Tratamento  18  33938 1885.44 6.0384 0.0000
Bloco        2   2783 1391.41 4.4562 0.0125
Residuo    262  81808  312.24              
Total      282 118529                      
------------------------------------------------------------------------
CV = 27.94 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  0.005607828 
ATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.9995446 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

Teste de Scott-Knott
------------------------------------------------------------------------
   Grupos Tratamentos   Medias
1       a          AT 84.50867
2       a         297 80.26267
3       a          HI 79.55800
4       b         290 74.42267
5       b         Mix 70.26867
6       b          BI 68.67936
7       b          58 68.16800
8       c         ADJ 64.15667
9       c        E585 61.55133
10      c          78 61.53867
11      c          64 61.13500
12      c        E414 59.56200
13      c        E174 58.91200
14      c        M121 58.50133
15      c        M230 55.36133
16      d        E486 53.57067
17      d        M442 50.78800
18      d        M267 48.14707
19      d         E48 42.65067
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>Transformação dos dados:</strong> como os dados atenderam a premissa de homocedasticidade, mas não atenderam a premissa de normalidade pelo teste SK, precisou realizar a transformação logarítmica dos dados (log + 0.5).</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-25_c71a0d86729cc3b134c3869e8d5086a9">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>inc3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(inc3<span class="sc">$</span>bloco)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(inc3<span class="sc">$</span>trat, <span class="fu">factor</span>(inc3<span class="sc">$</span>bloco), <span class="fu">log</span>(inc3<span class="sc">$</span>inc <span class="sc">+</span> <span class="fl">0.5</span>), <span class="at">quali =</span> (<span class="cn">TRUE</span>), <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>,<span class="at">sigF =</span> <span class="fl">0.05</span>, <span class="at">unfold =</span> <span class="cn">NULL</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL     SQ      QM     Fc   Pr&gt;Fc
Tratamento  18 11.105 0.61696 4.2718 0.00000
Bloco        2  0.422 0.21104 1.4612 0.23384
Residuo    262 37.840 0.14443               
Total      282 49.367                       
------------------------------------------------------------------------
CV = 9.3 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  1.490841e-15 
ATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.9999001 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

Teste de Scott-Knott
------------------------------------------------------------------------
   Grupos Tratamentos   Medias
1       a          AT 4.426526
2       a         297 4.377435
3       a          HI 4.348190
4       a         290 4.303842
5       a         Mix 4.229844
6       a          58 4.202431
7       b         ADJ 4.115889
8       b          BI 4.114462
9       b        E585 4.090761
10      b          64 4.063330
11      b        E414 4.050855
12      b        E174 4.034805
13      b          78 4.032324
14      b        M121 4.026069
15      b        M230 3.983154
16      b        E486 3.926587
17      b        M442 3.897683
18      c        M267 3.702856
19      c         E48 3.688126
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Assim como para a variável severidade, os tratamentos foram agrupados em três grupos estatisticamente diferentes - “a”, “b” e “c”, sendo apenas 2 tratamentos agrupados em “c” com as menores médias e, portanto, considerados os melhores tratamentos.</p>
<p><strong>Visualização dos agrupamentos em boxplot</strong>:</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-26_af57cb22cf691182ff40cdc3c85612ff">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>inc3 <span class="ot">&lt;-</span> inc3 <span class="sc">|&gt;</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="fu">case_when</span>(</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"AT"</span>, <span class="st">"HI"</span>, <span class="st">"297"</span>, <span class="st">"290"</span>, <span class="st">"58"</span>, <span class="st">"Mix"</span>) <span class="sc">~</span> <span class="st">"Group A"</span>,</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"BI"</span>,<span class="st">"ADJ"</span>, <span class="st">"E486"</span>, <span class="st">"E585"</span>, <span class="st">"E174"</span>, <span class="st">"M230"</span>, <span class="st">"M442"</span>, <span class="st">"M121"</span>, <span class="st">"64"</span>, <span class="st">"78"</span>, <span class="st">"E414"</span>) <span class="sc">~</span> <span class="st">"Group B"</span>,</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>    trat <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"M267"</span>, <span class="st">"E48"</span>) <span class="sc">~</span> <span class="st">"Group C"</span>))</span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Gráfico boxplot da resposta severidade, coloridos por grupos:</span></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(c2, <span class="fu">aes</span>(trat, sev, <span class="at">fill =</span> grupo)) <span class="sc">+</span></span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="st">"AT"</span>, <span class="st">"HI"</span>, <span class="st">"BI"</span>, <span class="st">"297"</span>, <span class="st">"58"</span>, <span class="st">"290"</span>, <span class="st">"ADJ"</span>, <span class="st">"E486"</span>, <span class="st">"E585"</span>, <span class="st">"E174"</span>, <span class="st">"M230"</span>, <span class="st">"Mix"</span>, <span class="st">"M442"</span>, <span class="st">"M121"</span>, <span class="st">"M267"</span>, <span class="st">"64"</span>, <span class="st">"78"</span>, <span class="st">"E414"</span>, <span class="st">"E48"</span>)) <span class="sc">+</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Treatments"</span>) <span class="sc">+</span></span>
<span id="cb53-15"><a href="#cb53-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Incidence (%)"</span>) <span class="sc">+</span></span>
<span id="cb53-16"><a href="#cb53-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">20</span>, <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb53-17"><a href="#cb53-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Group A"</span> <span class="ot">=</span> <span class="st">"#af8dc3"</span>, <span class="st">"Group B"</span> <span class="ot">=</span> <span class="st">"#67a9cf"</span>, <span class="st">"Group C"</span> <span class="ot">=</span> <span class="st">"#99d594"</span>), <span class="at">name =</span> <span class="st">"Treatments groups"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="altura-de-planta" class="level2">
<h2 class="anchored" data-anchor-id="altura-de-planta">Altura de planta</h2>
<section id="preparo-pré-análise-2" class="level3">
<h3 class="anchored" data-anchor-id="preparo-pré-análise-2">Preparo pré-análise</h3>
<p><strong>Importação de dados:</strong> os dados foram atribuídos ao objeto <code>altura</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-27_b69a253ed8f5af0ec6682e31218e5e3d">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>altura <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733"</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>altura</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 285 × 7
   trat  bloco planta   alt n_folhas folhas_ferrugem   inc
   &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;
 1 E585      1      1  40         27              12  44.4
 2 E585      1      2  32.9       46              19  41.3
 3 E585      1      3  39         15               9  60  
 4 E585      1      4  38.5       52              23  44.2
 5 E585      1      5  42         29              10  34.5
 6 E585      2      6  33         34              26  76.5
 7 E585      2      7  33         31              24  77.4
 8 E585      2      8  41         19              15  78.9
 9 E585      2      9  24.9       20              13  65  
10 E585      2     10  31         30              20  66.7
# ℹ 275 more rows</code></pre>
</div>
</div>
<p><strong>Arrumando os dados:</strong> como o data frame tem mais de uma variável resposta, fez-se necessário selecionar apenas os dados referentes a altura de plantas e também filtrar as células com ausência de dados no data frame para evitar erros.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-28_770ced0fdabf2202a2ce8e231c64287c">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>alt1 <span class="ot">&lt;-</span> altura <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a> dplyr<span class="sc">::</span><span class="fu">select</span>(trat, bloco, alt) <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(alt <span class="sc">!=</span> <span class="st">"NA"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="análise-exploratória-dos-dados-2" class="level3">
<h3 class="anchored" data-anchor-id="análise-exploratória-dos-dados-2">Análise exploratória dos dados</h3>
<p><strong>Boxplot:</strong> foi feito a plotagem dos dados em um boxplot para ver o comportamento da variável nos diferentes tratamentos. Os tratamentos foram ordenados, por meio da função <code>reorder</code>, da maior para a menor altura de planta.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-29_26b57d088c62dccf16269b1ec9601ca0">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>alt1 <span class="sc">|&gt;</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">reorder</span>(trat, alt), alt))<span class="sc">+</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()<span class="sc">+</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">60</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Boxplot com média dos dados:</strong> os valores ausentes foram filtrados, os dados de altura de plantas agrupados pelos tratamentos (trat) e a média e o desvio padrão da variável resposta foram calculados. Após isso, a plotagem do boxplot foi feita com os valores de média e a barra de erro foi inserida.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-30_ba2b6688196e480f97279f0cdb357e03">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>alt2 <span class="ot">&lt;-</span> alt1 <span class="sc">|&gt;</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(alt)) <span class="sc">|&gt;</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat) <span class="sc">|&gt;</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">alt_mean =</span> <span class="fu">mean</span>(alt),</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">alt_sd =</span> <span class="fu">sd</span>(alt))</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>alt2 <span class="sc">|&gt;</span></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="fu">reorder</span>(trat, alt_mean), alt_mean))<span class="sc">+</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> alt_mean<span class="sc">-</span>alt_sd, <span class="at">ymax =</span> alt_mean<span class="sc">+</span>alt_sd), <span class="at">width=</span> <span class="dv">0</span>, <span class="at">alpha =</span> <span class="dv">1</span>)<span class="sc">+</span></span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">""</span>, <span class="at">x=</span><span class="st">"Treatments"</span>, <span class="at">y =</span> <span class="st">"Plant height (cm)"</span>)<span class="sc">+</span></span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">100</span>, <span class="dv">10</span>), <span class="at">limits =</span> <span class="fu">c</span>(<span class="dv">20</span>, <span class="dv">60</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análise-estatística-e-teste-de-hipóteses-2" class="level3">
<h3 class="anchored" data-anchor-id="análise-estatística-e-teste-de-hipóteses-2">Análise estatística e teste de hipóteses</h3>
<ul>
<li><p>Hipótese nula (H0): a altura das plantas é igual para todos os tratamentos.</p></li>
<li><p>Hipótese alternativa (Ha): pelo menos um dos tratamentos apresenta uma média de altura das plantas menor do que a média dos demais tratamentos.</p></li>
</ul>
<p><strong>ANOVA:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-31_6c95f0aa1f63437fb70ebeb559e6854c">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>alt3 <span class="ot">&lt;-</span> alt1 <span class="sc">|&gt;</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(alt <span class="sc">!=</span> <span class="st">"NA"</span>)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>alt3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(alt3<span class="sc">$</span>bloco)</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>aov2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(alt <span class="sc">~</span> trat <span class="sc">+</span> <span class="fu">factor</span>(bloco), <span class="at">data =</span> alt3)</span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aov2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value Pr(&gt;F)  
trat           18    999   55.51   1.233 0.2347  
factor(bloco)   2    216  107.76   2.393 0.0934 .
Residuals     262  11799   45.04                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Com base no resultado da ANOVA, o p-valor para a variável trat é maior que o nível de significância (0,05), o que indica que não há diferença estatistica significativa, portanto, deve-se aceitar a hipótese nula de que a média de altura é igual para todos os tratamentos.</p>
<p><strong>Histograma dos resíduos:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-32_daf9287402c4da0a2dc7fda2712abc70">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span> (aov2<span class="sc">$</span>residuals)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O histogrma dos resíduos da ANOVA para a variável altura de planta mostra que a distribuição dos dados é aproximadamente normal.</p>
<p><strong>Checagem das premissas:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-33_e8da1eaef1a1eb8d6a703e1066fa8c8d">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(aov2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Non-normality of residuals detected (p = 0.015).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(aov2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.812).</code></pre>
</div>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">simulateResiduals</span>(aov2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Os dados apresentaram-se homocedásticos, porém, não foram considerados normais pela análise do pacote <code>performance</code>. Contudo, na análsie gráfica pelo <code>DHARMa</code>, os dados atenderam ambas as premissas, assim como no caso da variável resposta incidência analisada anteriormente. Assim sendo, não é necessário submeter os dados de altura de planta a transformação.</p>
<p><strong>Agrupamento de medias:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-34_8f0db100b09c7fbf4cb86b924ddd569e">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>alt3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(alt3<span class="sc">$</span>bloco)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(alt3<span class="sc">$</span>trat, <span class="fu">factor</span>(alt3<span class="sc">$</span>bloco), alt3<span class="sc">$</span>alt, <span class="at">quali =</span> <span class="cn">TRUE</span>, <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL      SQ      QM     Fc    Pr&gt;Fc
Tratamento  18   999.2  55.513 1.2327 0.234654
Bloco        2   215.5 107.764 2.3929 0.093359
Residuo    262 11799.2  45.035                
Total      282 13013.9                        
------------------------------------------------------------------------
CV = 19.4 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  0.01481312 
ATENCAO: a 5% de significancia, os residuos nao podem ser considerados normais!
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.7716508 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

De acordo com o teste F, as medias nao podem ser consideradas diferentes.
   Niveis   Medias
1     290 31.83333
2     297 34.10000
3      58 33.33333
4      64 33.53571
5      78 29.59333
6     ADJ 36.26667
7      AT 33.82667
8      BI 35.22143
9    E174 35.63333
10   E414 34.40000
11    E48 37.33333
12   E486 34.66667
13   E585 37.05333
14     HI 35.33333
15   M121 34.28667
16   M230 36.48000
17   M267 37.10000
18   M442 33.48000
19    Mix 33.61333
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p><strong>Transformação dos dados:</strong> como os dados atenderam a premissa de homocedasticidade, mas não a premissa de normalidade, realizou-se a transformação logarítmica dos dados.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-35_8f87a25d41bc3a52da31ac18abdd3dbe">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>alt3<span class="sc">$</span>bloco <span class="ot">=</span> <span class="fu">as.factor</span>(alt3<span class="sc">$</span>bloco)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dbc</span>(alt3<span class="sc">$</span>trat, <span class="fu">factor</span>(alt3<span class="sc">$</span>bloco), <span class="fu">log</span>(alt3<span class="sc">$</span>alt <span class="sc">+</span> <span class="fl">0.5</span>), <span class="at">quali =</span> <span class="cn">TRUE</span>, <span class="at">mcomp =</span> <span class="st">"sk"</span>, <span class="at">sigT =</span> <span class="fl">0.05</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>------------------------------------------------------------------------
Quadro da analise de variancia
------------------------------------------------------------------------
            GL      SQ       QM     Fc    Pr&gt;Fc
Tratamento  18  0.9402 0.052232 1.3882 0.136747
Bloco        2  0.1910 0.095508 2.5385 0.080929
Residuo    262  9.8576 0.037625                
Total      282 10.9888                         
------------------------------------------------------------------------
CV = 5.48 %

------------------------------------------------------------------------
Teste de normalidade dos residuos 
valor-p:  0.09134266 
De acordo com o teste de Shapiro-Wilk a 5% de significancia, os residuos podem ser considerados normais.
------------------------------------------------------------------------

------------------------------------------------------------------------
Teste de homogeneidade de variancia 
valor-p:  0.8681911 
De acordo com o teste de oneillmathews a 5% de significancia, as variancias podem ser consideradas homogeneas.
------------------------------------------------------------------------

De acordo com o teste F, as medias nao podem ser consideradas diferentes.
   Niveis   Medias
1     290 3.457935
2     297 3.526061
3      58 3.504822
4      64 3.498774
5      78 3.379349
6     ADJ 3.581788
7      AT 3.516233
8      BI 3.560195
9    E174 3.578536
10   E414 3.535305
11    E48 3.624740
12   E486 3.535825
13   E585 3.614540
14     HI 3.568171
15   M121 3.529186
16   M230 3.591115
17   M267 3.610197
18   M442 3.510648
19    Mix 3.510275
------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>De acordo com o teste F, realizado dentro do teste SK, as médias dos tratamentos não podem ser consideradas diferentes para a altura de plantas, portanto, não houve agrupamento, já que são estatisticamente iguais.</p>
<p><strong>Tabela de médias pelo teste Scott-Knott</strong></p>
<p>Médias de 19 tratamentos testados para controle da ferrugem do café para 3 variáveis resposta agrupadas pelo teste Scott-Knott.</p>
<table class="table">
<thead>
<tr class="header">
<th>Tratamentos</th>
<th>Severidade</th>
<th>AACPD</th>
<th>Incidência</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>58</td>
<td>1.2149423 b</td>
<td>94.950 b</td>
<td>4.202431 a</td>
</tr>
<tr class="even">
<td>64</td>
<td>0.5988305 c</td>
<td>64.425 b</td>
<td>4.063330 b</td>
</tr>
<tr class="odd">
<td>78</td>
<td>0.5688595 c</td>
<td>82.350 b</td>
<td>4.032324 b</td>
</tr>
<tr class="even">
<td>290</td>
<td>1.1440346 b</td>
<td>113.225 b</td>
<td>4.303842 a</td>
</tr>
<tr class="odd">
<td>297</td>
<td>1.2878112 b</td>
<td>251.250 a</td>
<td>4.377435 a</td>
</tr>
<tr class="even">
<td>E48</td>
<td>0.3740960 c</td>
<td>12.025 b</td>
<td>3.688126 c</td>
</tr>
<tr class="odd">
<td>E174</td>
<td>0.9069136 b</td>
<td>43.975 b</td>
<td>4.034805 b</td>
</tr>
<tr class="even">
<td>E414</td>
<td>0.3786039 c</td>
<td>38.725 b</td>
<td>4.050855 b</td>
</tr>
<tr class="odd">
<td>E486</td>
<td>1.0184742 b</td>
<td>52.575 b</td>
<td>3.926587 b</td>
</tr>
<tr class="even">
<td>E585</td>
<td>0.9342449 b</td>
<td>107.075 b</td>
<td>4.090761 b</td>
</tr>
<tr class="odd">
<td>M121</td>
<td>0.7138208 c</td>
<td>59.800 b</td>
<td>4.026069 b</td>
</tr>
<tr class="even">
<td>M230</td>
<td>0.8677099 b</td>
<td>103.850 b</td>
<td>4.026069 b</td>
</tr>
<tr class="odd">
<td>M267</td>
<td>0.6545537 c</td>
<td>48.325 b</td>
<td>3.702856 c</td>
</tr>
<tr class="even">
<td>M442</td>
<td>0.7207828 c</td>
<td>63.025 b</td>
<td>3.897683 b</td>
</tr>
<tr class="odd">
<td>ADJ</td>
<td>1.0217011 b</td>
<td>104.850 b</td>
<td>4.115889 b</td>
</tr>
<tr class="even">
<td>AT</td>
<td>2.1292877 a</td>
<td>261.425 a</td>
<td>4.426526 a</td>
</tr>
<tr class="odd">
<td>BI</td>
<td>1.6465584 a</td>
<td>220.575 a</td>
<td>4.114462 b</td>
</tr>
<tr class="even">
<td>HI</td>
<td>1.9219884 a</td>
<td>134.650 b</td>
<td>4.348190 a</td>
</tr>
<tr class="odd">
<td>Mix</td>
<td>0.8643519 b</td>
<td>65.500 b</td>
<td>4.229844 a</td>
</tr>
</tbody>
</table>
<p>*Médias seguidas pela mesma letra, na mesma coluna, pertencem a um mesmo grupo (Scott-Knott). Médias transformadas (log) das variáveis severidade e incidência.</p>
</section>
</section>
</section>
<section id="análise-de-correlação" class="level1">
<h1>Análise de Correlação</h1>
<p>Como foram obtidas três variáveis respostas, além da AACPD calculada, e estas variáveis foram analisadas separadamente, tentou-se avaliar se essas variáveis estão correlacionadas, ou seja, se há uma associação entre elas. Por meio da análise de correlação, testou-se a seguinte hipótese:</p>
<ul>
<li><p>Hipótese nula (H0): não há correlação significativa entre as duas variáveis analisadas.</p></li>
<li><p>Hipótese alternativa (Ha): há uma correlação significativa entre as duas variáveis analisadas.</p></li>
</ul>
<section id="correlação-entre-severidade-e-aadpc" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-severidade-e-aadpc">Correlação entre severidade e AADPC</h2>
<p><strong>Preparo dos dados:</strong> para realizar a análise de correlação entre essas duas variáveis, primeiramente foi necessário igualar o conjunto de dados de severidade para a mesma quantidade de linhas do conjunto de AACPD. Para esta análise, os dados de severidade foram atríbuidos ao conjunto <code>corsev</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-36_89b4d9f87ef5f3ef764aaf3d91c63507">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>corsev <span class="ot">&lt;-</span> controle <span class="sc">|&gt;</span> </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(sev <span class="sc">!=</span> <span class="st">"NA"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trat, bloco) <span class="sc">|&gt;</span> </span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sev_mean =</span> <span class="fu">mean</span>(sev))</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>corsev</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 57 × 3
# Groups:   trat [19]
   trat  bloco sev_mean
   &lt;chr&gt; &lt;dbl&gt;    &lt;dbl&gt;
 1 290       1    2.69 
 2 290       2    1.85 
 3 290       3    0.914
 4 297       1    5.45 
 5 297       2    1.23 
 6 297       3    2.07 
 7 58        1    3.50 
 8 58        2    1.16 
 9 58        3    1.21 
10 64        1    2.26 
# ℹ 47 more rows</code></pre>
</div>
</div>
<p><strong>Teste de correlação</strong>: para realizar o teste de correlação, usou-se a função <code>cor.test</code>, que é parte do pacote base do R.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-37_6f261de5c1fee741c3e8d37897263cd3">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(corsev<span class="sc">$</span>sev_mean, c3<span class="sc">$</span>AACPD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  corsev$sev_mean and c3$AACPD
t = 13.248, df = 55, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.7921156 0.9232368
sample estimates:
      cor 
0.8725825 </code></pre>
</div>
</div>
<p>O p-valor da análise da relação entre as variáveis foi menor do que o nível de significância (0,05), indicando que a hipótese nula deve ser rejeitada. Aliado a isso, a análise de correlação para as variáveis severidade e AACPD obteve um coeficiente de correlação de Pearson estimado de 0.87, sendo considerada uma correlação positiva e próxima de 1, portanto, uma correlação alta. Isso demonstra que há uma relação forte entre essas duas variáveis e que quanto mais alta a severidade média da doença, maior é a área abaixo da curva de progresso da doença.</p>
<p><strong>Visualização gráfica da correlação</strong>:</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-38_d3a99c862c9c15d2d67941fc8c87a84e">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(corsev<span class="sc">$</span>sev_mean, c3<span class="sc">$</span>AACPD)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlação-entre-incidência-e-altura-de-planta" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-incidência-e-altura-de-planta">Correlação entre incidência e altura de planta</h2>
<p><strong>Importação dos dados:</strong> O teste de correlação poderia ter sido feito diretamente usando os conjuntos <code>inc3$inc</code> e <code>alt3$alt</code>, porém, não seria possível visualizar as variáveis graficamente. Então, para visualizar a possibilidade da correlação antes do teste, realizou-se a importação dos dados novamente para se trabalhar com ambas as variáveis em um único conjunto. Estas variáveis foram atríbuidas ao objeto <code>cor</code>. A função <code>head</code> foi utilizada para chamar as primeiras linhas do conjunto de dados e confirmar que os dados foram carregados de forma correta.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-39_da57e1eb60437dedf56811839c5b9c0a">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>cor <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1007691733"</span>)</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(cor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 7
  trat  bloco planta   alt n_folhas folhas_ferrugem   inc
  &lt;chr&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt; &lt;dbl&gt;
1 E585      1      1  40         27              12  44.4
2 E585      1      2  32.9       46              19  41.3
3 E585      1      3  39         15               9  60  
4 E585      1      4  38.5       52              23  44.2
5 E585      1      5  42         29              10  34.5
6 E585      2      6  33         34              26  76.5</code></pre>
</div>
</div>
<p><strong>Visualização e análise exploratória:</strong> plotou-se os dados em um gráfico de dispersão usando a função <code>geom_point</code>, contendo em sua estética ambas as variáveis resposta. A camada com a função <code>geom_smooth</code> foi utilizada para criar uma linha de tendência. Dentro desta função, foi especificado que as barras de erro não serão exibidas no gráfico (se = “F”) e que o método de regressão linear deve ser usado para ajustar a linha (method = “lm”).</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-40_c5f16ae69c33c5a7bfd88c1fc6cd13c4">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>cor <span class="sc">|&gt;</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(inc, alt))<span class="sc">+</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> F, <span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Disease incidence (%)"</span>, <span class="at">y =</span> <span class="st">"Plant height (cm)"</span>) <span class="sc">+</span></span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Relationship between disease incidence and plant height"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Baseado apenas na análise visual do gráfico de correlação, é possível prever que, pela direção da linha de melhor ajuste, existe uma correlação negativa entre as variáveis analisadas. A inclinação da linha parece sugerir que essa correlação não é muito forte.</p>
<p><strong>Teste de correlação:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-41_c814f283d995fce420690a63221791fb">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>cor2 <span class="ot">&lt;-</span> cor <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(trat, bloco, inc, alt) <span class="sc">|&gt;</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(alt <span class="sc">!=</span> <span class="st">"NA"</span>)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(cor2<span class="sc">$</span>inc, cor2<span class="sc">$</span>alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  cor2$inc and cor2$alt
t = -1.0215, df = 281, p-value = 0.3079
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.17617476  0.05616917
sample estimates:
        cor 
-0.06082672 </code></pre>
</div>
</div>
<p>O p-valor foi maior do que o nível de significância (0,05), indicando que a hipótese nula deve ser aceita. Comprovando a análise visual, o coeficiente de correlação de Pearson estimado na análise de correlação para as variáveis incidência e altura de planta foi de -0.06082672, um valor negativo e próximo de zero, o que indica que as variáveis estão negativamnete correlacionadas e possuem uma relação fraca, até mesmo próxima a inexistência. Isso quer dizer que à medida que a incidência aumenta, a altura da planta tende a diminuir.</p>
<p><strong>Visualização gráfica do resultado da correlação:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-42_4e11f4273605f389b297b843ce9f4929">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cor2<span class="sc">$</span>inc, cor2<span class="sc">$</span>alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="correlação-entre-severidade-e-altura-de-planta" class="level2">
<h2 class="anchored" data-anchor-id="correlação-entre-severidade-e-altura-de-planta">Correlação entre severidade e altura de planta</h2>
<p><strong>Importação dos dados:</strong> como originalmente as variáveis resposta severidade e altura de planta pertenciam a data frames diferentes, um novo data frame foi feito contendo ambas as variáveis para viabilizar a realização da análise de correlação. Os dados foram atríbuidos ao conjunto <code>sev_cor</code>.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-43_4a953b6ab18cb3d05d8a3b7c56c28f08">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>sev_cor <span class="ot">&lt;-</span> <span class="fu">gsheet2tbl</span>(<span class="st">"https://docs.google.com/spreadsheets/d/1bw5wWl5dZHis32FU8C60o1xT4HbXqeC9/edit#gid=1796689464"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sev_cor)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  trat  bloco sev_final   alt
  &lt;chr&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;
1 E585      1 3.20       40  
2 E585      1 1.47       32.9
3 E585      1 0.48       39  
4 E585      1 3.65       38.5
5 E585      1 3.95       42  
6 E585      2 5.7        33  </code></pre>
</div>
</div>
<p><strong>Arrumando os dados:</strong> para que não ocorressem erros durante a análise, os dados foram atríbuidos a um novo objeto chamado <code>sev_alt</code>, os dados ausentes foram filtrados e a variável severidade foi transformada de caractere para número por meio da função <code>mutate</code>. Após isso, os dados foram plotados em um gráfico de dispersão.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-44_bb28f8e09cd0dfb9b08c255f3c7bf490">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>sev_alt <span class="ot">&lt;-</span> sev_cor <span class="sc">|&gt;</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(alt <span class="sc">!=</span> <span class="st">"NA"</span>) <span class="sc">|&gt;</span></span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sev_final =</span> <span class="fu">as.numeric</span>(sev_final))</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>sev_alt <span class="sc">|&gt;</span></span>
<span id="cb84-6"><a href="#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(sev_final, alt))<span class="sc">+</span></span>
<span id="cb84-7"><a href="#cb84-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb84-8"><a href="#cb84-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">se =</span> F, <span class="at">method =</span> <span class="st">"lm"</span>)<span class="sc">+</span></span>
<span id="cb84-9"><a href="#cb84-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Retendo-se apenas a análise do gráfico, a direção da linha indica a tendência de uma correlação positiva entre as variáveis, mas a inclinação da linha parece demonstrar que essa correlação é fraca.</p>
<p><strong>Teste de correlação:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-45_47951c49f4214c8a6a8d19dfa2b479a0">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(sev_alt<span class="sc">$</span>sev_final, sev_alt<span class="sc">$</span>alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  sev_alt$sev_final and sev_alt$alt
t = 1.1115, df = 281, p-value = 0.2673
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.05082925  0.18135886
sample estimates:
       cor 
0.06616037 </code></pre>
</div>
</div>
<p>O valor de p (0.2673) é maior que o nível de significância comumente adotado (0, 05), o que sugere que não há uma correlação estatisticamente significativa entre as variáveis. Além disso, o coeficiente de correlação de Pearson foi de 0.06616037, um valor próximo de zero, indicando uma correlação fraca ou inexistente entre as variáveis severidade e altura de planta.</p>
<p><strong>Visualização gráfica do resultado da correlação:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-46_8794fb3bcd77110a5699b71c9ceb83a7">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sev_alt<span class="sc">$</span>sev_final, sev_alt<span class="sc">$</span>alt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="análise-de-regressão" class="level1">
<h1>Análise de Regressão</h1>
<p>A análise de regressão linear foi realizada no intuíto de identificar e quantificar a relação entre as variáveis. Na análise de regressão, testou-se a hipótese nula de que não há relação entre a variável independente e a variável dependente. A hipótese alternativa é que há uma relação entre a variável independente e a variável dependente.</p>
<section id="efeito-da-severidade-na-altura-de-planta" class="level2">
<h2 class="anchored" data-anchor-id="efeito-da-severidade-na-altura-de-planta">Efeito da severidade na altura de planta</h2>
<p>Realizamos uma análise de regressão para saber se a altura da planta tem relação com a severidade da doença, ou seja, se a variável altura de planta é dependente da severidade. Nesse caso, foi utilizado os valores da severidade final.</p>
<p><strong>Visualização e análise exploratória:</strong></p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-47_1f102654c2922dd263a504095e66657d">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a>sev_alt <span class="sc">|&gt;</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(alt,sev_final, <span class="at">color =</span> trat))<span class="sc">+</span></span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()<span class="sc">+</span></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span><span class="st">"lm"</span>, <span class="at">se =</span>F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="T_Hemileia_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Teste:</strong> o teste de regressão foi realizado utilizando a função <code>lm</code>, que faz parte do pacote base do R. A função <code>summary</code> foi usada para gerar um quadro de resumo com o resultado do teste.</p>
<div class="cell" data-hash="T_Hemileia_cache/html/unnamed-chunk-48_082f8d7679af1d1711a83505b2302759">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a>reg <span class="ot">&lt;-</span> <span class="fu">lm</span>(alt <span class="sc">~</span> sev_final, <span class="at">data =</span> sev_alt)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb89-3"><a href="#cb89-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = alt ~ sev_final, data = sev_alt)

Residuals:
     Min       1Q   Median       3Q      Max 
-13.2851  -5.2659  -0.2148   5.0985  18.5103 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 34.24723    0.50534  67.770   &lt;2e-16 ***
sev_final    0.09237    0.08311   1.111    0.267    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 6.79 on 281 degrees of freedom
Multiple R-squared:  0.004377,  Adjusted R-squared:  0.0008341 
F-statistic: 1.235 on 1 and 281 DF,  p-value: 0.2673</code></pre>
</div>
</div>
<p>A análise de regressão indica que a severidade final não tem um efeito estatisticamente significativo na altura das plantas. O p-valor da variável severidade final é de 0.267, o que mostra a falta de evidências estatisticamente significativas de uma relação linear entre as variáveis. Aliado a isso, o valor do coeficiente de determinação (R²), que indica quanto a variável resposta altura de planta é explicada pela variável severidade final, deu muito baixo (0.004377).</p>
</section>
</section>
<section id="conclusão" class="level1">
<h1>Conclusão</h1>
<p>Considerando os agrupamentos de média dos tratamentos para a variável resposta severidade, os melhores tratamentos no controle da doença (menores médias) foram: M442, M121, M267, 64, 78, E414 e E48. Já para a incidência, apenas dois tratamentos apresentaram as menores médias. Pela AACPD, mais de 8 tratamentos foram considerados estatísticamente iguais e agrupados como tendo as menores médias dentre eles, a a maioria dos considerados melhores baseado na severidade: 64, M442, M121, E486, M267, E174, E414 e E48.</p>
<p>Diante dos resultados obtidos, conclui-se que os dados são inconclusivos e não possuem confiabilidade suficiente, uma vez que apresentam um alto coeficiente de variação e desvio padrão para a principal variável resposta analisada, fazendo com que haja uma alta variabilidasde entre os blocos. Recomenda-se a repetição do experimento utilizando um maior número de repetições para reduzir o CV e o erro experimetal. Os resultados obtidos nestas análises podem ser úteis para a exclusão dos piores tratamentos testados e seleção dos melhores tratamentos para novos experimentos.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright 2023, Nívia Maria Pereira</div>   
  </div>
</footer>



</body></html>